Repository the-turing-way/the-turing-way, pull requests merged in 2019-10, with the labels that each got.

#680 Remove template text from the chapter on credit
  book/content/credit/credit.md
Labels: typo-fix

#679 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: typo-fix

#715 [QuickFix] Add youtube links to collaboration cafe page
  project_management/online-collaboration-cafe.md
Labels: community, project management

#672 [Quick Fix] Add travis badge to readme
  README.md
Labels: comms

#713 Newsletter for Oct 2019
  communications/newsletters/images/Tweet-OpenScienceFair2019.png
  communications/newsletters/images/Tweet-UKRSE19.png
  communications/newsletters/newsletter_07_Oct2019.md
Labels: Outreach, community

#699 Add barrier 1 (plead the fifth) to barriers.md in reproducibility chapter
  book/content/reproducibility/04/barriers.md
Labels: book

#720 Update licence to include both MIT and CC-BY
  LICENSE
  LICENSE.md
Labels: project management
