Repository the-turing-way/the-turing-way, pull requests merged in 2019-06, with the labels that each got.

#611 [Ready for review] Acknowledge new user fears
  README.md
Labels: book-dash-ldn

#644 Add talk from OR Lancaster
  conferences/README.md
  conferences/presentations/ORLancaster_20190604/Whitaker_ORLancaster_June2019.pdf
Labels: community

#452 [Ready for review] Address remaining issues for Make chapter (closes #409)
  book/content/figures/make/report_all_genres.png
  book/content/figures/make/research_dag.png
  book/content/make/make.md
Labels: book

#537 [Ready for review] Updates to Boost your Research Reproducibility workshop folder for JOSE submission
  CONTRIBUTING.md
  workshops/boost-research-reproducibility-binder/README.md
  workshops/boost-research-reproducibility-binder/agenda.md
  workshops/boost-research-reproducibility-binder/feedback/report.md
  workshops/boost-research-reproducibility-binder/figures/binder_ldn_tweet1.png
  workshops/boost-research-reproducibility-binder/figures/binder_ldn_tweet2.png
  workshops/boost-research-reproducibility-binder/figures/binder_ldn_tweet3.png
  workshops/boost-research-reproducibility-binder/figures/binder_ldn_tweet4.png
  workshops/boost-research-reproducibility-binder/figures/binder_ldn_tweet5.png
  workshops/boost-research-reproducibility-binder/figures/binder_man_tweet1.png
  workshops/boost-research-reproducibility-binder/figures/binder_man_tweet2.png
  workshops/boost-research-reproducibility-binder/instructor_guide.md
  workshops/boost-research-reproducibility-binder/paper.bib
  workshops/boost-research-reproducibility-binder/paper.md
Labels: comms, project management
