Repository the-turing-way/the-turing-way, pull requests merged in 2019-02, with the labels that each got.

#187 Add link to newsletter in README
  README.md
Labels: community

#188 Format two comments into one in PR issue template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: project management

#194 Move prerequisites to start of chapter
  chapters/reproducibility.md
  chapters/version_control.md
  templates/CHAPTER_TEMPLATE.md
Labels: book

#236 Add readme for workshops folder
  workshops/README.md
Labels: comms, project management, workshops
