Repository the-turing-way/the-turing-way, pull requests merged in 2019-01, with the labels that each got.

#106 First draft of abstract for UKRI Cloud Workshop demonstration
  conferences/abstracts/UKRI-cloud-workshop-abstract.md
Labels: community

#111 UKRI Cloud Workshop Abstract
  CONTRIBUTING.md
  conferences/abstracts/UKRI-cloud-workshop-abstract.md
Labels: comms

#113 Update to UKRI abstract
  conferences/abstracts/UKRI-cloud-workshop-abstract.md
Labels: comms

#119 Create collaborations-workshop-2019-abstract.md
  conferences/abstracts/UKRI-cloud-workshop-abstract.md
  conferences/abstracts/collaborations-workshop-2019-abstract.md
Labels: comms

#152 [Ready for Review] Workshop Adverts
  project_management/workshop_advert.md
Labels: comms, workshops

#159 Add KW preferred contact to ways of working
  ways_of_working.md
Labels: project management

#150 [Ready for review] Reproducibility chapter
  chapters/reproducibility.md
Labels: book

#140 [Ready for review] Develop open science chapter
  chapters/open_science.md
  chapters/version_control.md
  figures/figure_list.md
  figures/open_access_citatations.jpg
  figures/open_umbrealla.png
  project_management/dissemination_plan.md
  project_management/resources.md
  project_management/workshop_advert.md
  ways_of_working.md
Labels: book
