Repository the-turing-way/the-turing-way, pull requests merged in 2020-10, with the labels that each got.

#1344 update url to image after changing my GitHub name
  workshops/boost-research-reproducibility-binder/reports/workshop_report_20200131.md
Labels: PR: reviewed-approved

#1336 typo fix
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
Labels: PR: reviewed-approved

#1327 Create newsletter for September 2020
  communications/newsletters/images/Tweet-1000-Sep2020.png
  communications/newsletters/images/Tweet-Ismael-Sep2020.png
  communications/newsletters/images/Tweet-KW-Sep2020.png
  communications/newsletters/images/Tweet-OLS-Sep2020.png
  communications/newsletters/images/Tweet-collage-Sep2020.png
  communications/newsletters/images/Tweet-collage-Sep2020.pptx
  communications/newsletters/images/Tweet-elixir-Sep2020.png
  communications/newsletters/images/turingway-singleslide-Sep2020.png
  communications/newsletters/newsletter_17_Sept2020.md
Labels: PR: reviewed-approved

#1352 Update contributors.md with Laura, Sophia and Paul's details
  contributors.md
Labels: PR: partially-approved

#1350 Reduce image sizes to lower than 1MB
  book/website/figures/bookdash.png
  book/website/figures/communication.jpg
  book/website/figures/reproducibility.jpg
Labels: PR: reviewed-approved

#1353 Update contributors to add my links and bio
  contributors.md
Labels: PR: reviewed-approved

#1314 Update online-collaboration-cafe table with the date and time for 2020
  project_management/online-collaboration-cafe.md
Labels: PR: reviewed-approved

#1272 Fix minor Markdown syntax error
  book/website/reproducible-research/vcs/vcs-git-merge.md
Labels: Hacktoberfest, PR: reviewed-approved, PR: unreviewed, good first PR review

#1356 Create README-Dutch.md
  README-Dutch.md
Labels: Hacktoberfest, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, review request, translation

#1349 [Ready for review] README Translation to Brazilian Portuguese
  README-pt-BR.md
Labels: Hacktoberfest, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, translation

#1387 create a folder for all the translated READMEs and remove redundant bits
  README-Dutch.md
  README-pt-BR.md
  README-translated/README-Dutch.md
  README-translated/README-Portuguese.md
  README.md
Labels: PR: reviewed-approved

#1397 Added bio in contributors.md
  contributors.md
Labels: PR: reviewed-approved

#1389 Fix dead link in rdm-spreadsheets
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
Labels: PR: reviewed-approved, good first PR review

#1338 [Ready to review] README Spanish translation
  README-translated/README-Dutch.md
  README-translated/README-Portuguese.md
  README-translated/README-Spanish.md
  README.md
Labels: Hacktoberfest, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, translation

#1401 Updated eScience center contributions
  contributors.md
Labels: PR: unreviewed

#1357 Update contributors.md with contributors roles and missing bios
  book/website/afterword/contributors-record.md
  book/website/community-handbook/acknowledgement/acknowledgement-record.md
  contributors.md
Labels: PR: unreviewed, community, idea-for-discussion

#1402 Update acknowledgement-examples.md
  book/website/community-handbook/acknowledgement/acknowledgement-examples.md
Labels: PR: reviewed-approved

#1423 Update coc-reporting.md
  book/website/community-handbook/coc/coc-reporting.md
Labels: PR: reviewed-approved

#1305 Create GSoD 2020 Project Proposal
  communications/GSOD-applications/GSoD-2020-Project-Proposal.md
Labels: PR: unreviewed, project management

#1418 Remove auto-formatting section and outdated image referencing in the style guide
  book/website/community-handbook/style.md
  book/website/community-handbook/style/style-figures.md
Labels: PR: unreviewed

#1403 Update coc-enforcement.md
  book/website/community-handbook/coc/coc-enforcement.md
Labels: PR: reviewed-approved

#1426 Fixes Markdown formatting of non-consecutive headers: persona-contributors.md , open-source.md
  book/website/project-design/persona/persona-contributors.md
  book/website/reproducible-research/open/open-source.md
Labels: PR: reviewed-approved

#1431 Fix non-consecutive headers: CI subchapters
  book/website/reproducible-research/ci/ci-options.md
  book/website/reproducible-research/overview/overview-resources.md
Labels: PR: reviewed-approved

#1437 updated Fig.2 in chapter Managing a New Community and Team to MyST format
  book/website/collaboration/new-community.md
Labels: PR: unreviewed

#1430 Fix non-consecutive headers: open-access.md
  book/website/reproducible-research/open/open-access.md
Labels: PR: reviewed-approved

#1345 [Ready for review] README Italian translation (ciao, mondo!)
  README-translated/README-Italian.md
  README.md
Labels: Hacktoberfest, PR: reviewed-approved, PR: unreviewed, translation

#1444 fixed format (header, add syntax highlighting) vcs-git-merge.md
  book/website/reproducible-research/vcs/vcs-git-merge.md
Labels: PR: reviewed-approved

#1445 Changed heading labels from 4 to 3 and 3 to 2 in vcs-github.md
  book/website/reproducible-research/vcs/vcs-github.md
Labels: PR: reviewed-approved

#1449 merge data licence from different branch
  book/website/reproducible-research/licensing/licensing-data.md
Labels: PR: unreviewed

#1454 Correcting Paul Owoicho's contributors record
  book/website/afterword/contributors-record.md
Labels: PR: reviewed-approved

#1452 Create newsletter for Oct 2020: newsletter_18_Oct2020.md
  communications/newsletters/images/Paul-Oct2020.png
  communications/newsletters/images/Tweet-MGV-Oct2020.png
  communications/newsletters/images/Tweet-MOR-Oct2020.png
  communications/newsletters/images/Tweet-SB-Oct2020.png
  communications/newsletters/images/Tweet-SG-Oct2020.png
  communications/newsletters/images/Tweet-collage-Oct2020.png
  communications/newsletters/images/Tweet-readme-Oct2020.png
  communications/newsletters/images/Tweet-tw-Oct2020.png
  communications/newsletters/newsletter_18_Oct2020.md
Labels: PR: unreviewed

#1428 Fixed formatting on rdm-resources, added header and chapter summary
  book/website/reproducible-research/rdm/rdm-resources.md
Labels: PR: reviewed-approved

#1451 Update open-scholarship.md
  book/website/reproducible-research/open/open-scholarship.md
Labels: PR: reviewed-approved

#1472 Reduced the file sizes of three images in book/website/figures direct…
  book/website/figures/binder_comic.png
  book/website/figures/flipped_taj_mahal.png
  book/website/figures/welcome.jpg
Labels: PR: reviewed-approved

#1456 update OLS project details with right links and names
  open-life-science-mentoring/README.md
  open-life-science-mentoring/accessible-guidance/README.md
Labels: PR: reviewed-approved

#1462 Retrospective consistency for welcome.md
  book/website/welcome.md
Labels: PR: unreviewed, gsod2020

#1464 Typo Fix and Image conversion to MyST
  book/website/reproducible-research/reproducible-research.md
Labels: PR: reviewed-approved, gsod2020, reproducibility-book

#1453 This PR creates a directory to store GSoD 2020 related updates
  communications/GSOD-applications/2020-Paul-Owoicho/README.md
  communications/GSOD-applications/2020-Paul-Owoicho/check-in.md
Labels: PR: unreviewed, gsod2020

#1276 Update the format of the case study
  book/website/reproducible-research/case-studies/statistical-methods-manuscript.md
Labels: PR: reviewed-approved, case study, enhancement

#1400 Fixed Non-Consecutive Headers
  book/website/community-handbook/style.md
Labels: PR: unreviewed

#1474 Update Project Design section images and figures
  book/website/figures/personas.png
  book/website/figures/project-design.jpg
  book/website/project-design/persona.md
  book/website/project-design/project-design.md
Labels: PR: reviewed-approved

#1475 Fix citation
  book/website/reproducible-research/overview/overview-definitions.md
Labels: PR: reviewed-approved

#1463 Retrospective Consistency on RDM chapter of Guide to Reproducible Research
  book/website/_toc.yml
  book/website/reproducible-research/rdm.md
  book/website/reproducible-research/rdm/rdm-checklist.md
  book/website/reproducible-research/rdm/rdm-data.md
  book/website/reproducible-research/rdm/rdm-fair.md
  book/website/reproducible-research/rdm/rdm-metadata.md
  book/website/reproducible-research/rdm/rdm-resources.md
  book/website/reproducible-research/rdm/rdm-sharing.md
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
  book/website/reproducible-research/rdm/rdm-storage.md
  book/website/reproducible-research/rdm/rdm-stories.md
Labels: PR: partially-approved, gsod2020, reproducibility-book

#1460 Retrospective Consistency on Licensing Chapter of Guide to Reproducible Research
  book/website/_toc.yml
  book/website/figures/license-categories.jpg
  book/website/reproducible-research/licensing.md
  book/website/reproducible-research/licensing/licensing-checklist.md
  book/website/reproducible-research/licensing/licensing-compatibility.md
  book/website/reproducible-research/licensing/licensing-resources.md
  book/website/reproducible-research/licensing/licensing-software.md
Labels: PR: unreviewed, gsod2020, reproducibility-book

#1477 Fixed Non-Consecutive headers and Reduced image sizes to less than 1MB
  book/website/community-handbook/style/style-citing.md
  book/website/community-handbook/style/style-crossref.md
  book/website/figures/Provenance.jpg
  book/website/figures/ResearchCompendium.jpg
  book/website/figures/community.jpg
Labels: PR: unreviewed

#1476 Fix overview page header and reproducible research grammar
  book/website/reproducible-research/overview.md
  book/website/reproducible-research/reproducible-research.md
Labels: PR: reviewed-approved

#1479 Fixed heading level in open-notebooks.md issue #1409
  book/website/reproducible-research/open/open-notebooks.md
Labels: PR: reviewed-approved

#1483 Fixed non consecutive headers in open-data.md
  book/website/reproducible-research/open/open-data.md
Labels: PR: reviewed-approved

#1478 reduced 3 designated jpg files to below 1 MB
  book/website/figures/collaboration.jpg
  book/website/figures/data-ecosystem.jpg
  book/website/figures/distributed-collaboration.jpg
Labels: PR: reviewed-approved, hacktoberfest-accepted
