Repository the-turing-way/the-turing-way, pull requests merged in 2020-09, with the labels that each got.

#1312 Roll back the Acknowledgement chapter for reviewing
  book/website/_config.yml
  book/website/_toc.yml
  book/website/community-handbook/acknowledgement.md
  book/website/community-handbook/acknowledgement/acknowledgement-examples.md
  book/website/community-handbook/acknowledgement/acknowledgement-members.md
  book/website/community-handbook/acknowledgement/acknowledgement-record.md
  book/website/figures/logo/logo.png
  book/website/scripts/contributors.sh
  tests/no-bad-latin.py
Labels: PR: reviewed-approved, community-handbook

#1316 Update README.md
  book/website/ethical-research/README.md
Labels: PR: unreviewed

#1317 Update README.md
  book/website/ethical-research/README.md
Labels: PR: unreviewed

#1310 Moving Heidi's and Camila's personas to contributors file
  book/website/_toc.yml
  book/website/afterword/contributors-record.md
  contributors.md
Labels: PR: unreviewed

#1323 create OLS folder and add Ethics project folder
  open-life-science-mentoring/README.md
  open-life-science-mentoring/ethical-research-framework/README.md
Labels: PR: partially-approved

#1326 minor update to the acknowledgement chapter
  book/website/community-handbook/acknowledgement.md
Labels: PR: reviewed-approved

#1322 add Ismael-KG to contributors.md
  contributors.md
Labels: PR: unreviewed

#1325 Minor update in the Contributor's records to check if CI works
  book/website/afterword/contributors-record.md
  contributors.md
  tests/no-bad-latin.py
Labels: PR: unreviewed

#1324 Updated README.md
  open-life-science-mentoring/ethical-research-framework/README.md
Labels: PR: reviewed-approved

#1331 un-comment acknowledgement chapter and contributors file
  book/website/_toc.yml
Labels: PR: reviewed-approved

#1332 Update _toc.yml by correcting indentation issue
  book/website/_toc.yml
Labels: PR: reviewed-approved

#1279 Minor formatting in the spreadsheet subchapter
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
Labels: PR: reviewed-approved, good first PR review
