Repository the-turing-way/the-turing-way, pull requests merged in 2020-12, with the labels that each got.

#1458 Retrospective Consistency on Reproducible Environments Chapter of Guide to Reproducible Research
  book/website/_toc.yml
  book/website/figures/computational_environments.jpg
  book/website/reproducible-research/renv.md
  book/website/reproducible-research/renv/renv-binder.md
  book/website/reproducible-research/renv/renv-checklist.md
  book/website/reproducible-research/renv/renv-containers.md
  book/website/reproducible-research/renv/renv-options.md
  book/website/reproducible-research/renv/renv-package.md
  book/website/reproducible-research/renv/renv-resources.md
  book/website/reproducible-research/renv/renv-vm.md
  book/website/reproducible-research/renv/renv-yaml.md
Labels: PR: unreviewed, good first PR review, gsod2020, hacktoberfest-accepted, reproducibility-book

#1646 Chapter on Introducing Turing Way's Content Templates
  book/website/_toc.yml
  book/website/community-handbook/contributing.md
  book/website/community-handbook/contributing/contributing-templates.md
  book/website/community-handbook/contributing/contributing-workflow.md
Labels: PR: unreviewed, gsod2020

#1661 Add the newsletter draft for Novemeber 2020
  communications/newsletters/README.md
  communications/newsletters/images/2020-11-annotate-4.png
  communications/newsletters/images/2020-11-bookdash-3.png
  communications/newsletters/images/2020-11-kw-tweet-1.png
  communications/newsletters/images/2020-11-martina-6.png
  communications/newsletters/images/2020-11-poster-5.png
  communications/newsletters/images/2020-11-scrib-bug-2.png
  communications/newsletters/images/2020-11-tweet-collage-7.png
  communications/newsletters/newsletter_06_Sep2019.md
  communications/newsletters/newsletter_15_Jun2020.md
  communications/newsletters/newsletter_16_Jul2020.md
  communications/newsletters/newsletter_17_Sep2020.md
  communications/newsletters/newsletter_19_Nov2020.md
Labels: PR: reviewed-approved

#1657 Subchapter on Using Turing Way Stylesheets
  book/website/_toc.yml
  book/website/community-handbook/style/style-custom-styling.md
  book/website/community-handbook/style/style-special-content.md
Labels: PR: unreviewed, gsod2020

#1664 Revert "Subchapter on Using Turing Way Stylesheets"
  book/website/_toc.yml
  book/website/community-handbook/style/style-custom-styling.md
  book/website/community-handbook/style/style-more-styling.md
Labels: PR: reviewed-approved

#1642 Update Style Guide with Information about Content Blocks
  book/website/community-handbook/style/style-more-styling.md
Labels: PR: unreviewed, gsod2020

#1461 Retrospective consistency for Overview Chapter of the Guide to Reproducible Research
  book/website/_toc.yml
  book/website/reproducible-research/overview.md
  book/website/reproducible-research/overview/overview-benefit.md
  book/website/reproducible-research/overview/overview-checklist.md
  book/website/reproducible-research/overview/overview-definitions.md
  book/website/reproducible-research/overview/overview-resources.md
Labels: PR: unreviewed, good first PR review, gsod2020, hacktoberfest-accepted, reproducibility-book

#1465 Retrospective consistency for Version Control Chapter of the Guide to Reproducible Research
  book/website/_toc.yml
  book/website/reproducible-research/vcs.md
  book/website/reproducible-research/vcs/vcs-checklist.md
  book/website/reproducible-research/vcs/vcs-data.md
  book/website/reproducible-research/vcs/vcs-git-branches.md
  book/website/reproducible-research/vcs/vcs-git-commit.md
  book/website/reproducible-research/vcs/vcs-git-compare.md
  book/website/reproducible-research/vcs/vcs-git-merge.md
  book/website/reproducible-research/vcs/vcs-git-summary.md
  book/website/reproducible-research/vcs/vcs-git.md
  book/website/reproducible-research/vcs/vcs-github.md
  book/website/reproducible-research/vcs/vcs-personal-stories.md
  book/website/reproducible-research/vcs/vcs-resources.md
  book/website/reproducible-research/vcs/vcs-workflow.md
Labels: PR: unreviewed, good first PR review, gsod2020, hacktoberfest-accepted, reproducibility-book

#1665 restore custom styling chapter under style guide
  book/website/_toc.yml
  book/website/community-handbook/style/style-custom-styling.md
Labels: PR: reviewed-approved

#1667 Update the open research chapter by changing heading "Motivation and Background"
  book/website/reproducible-research/open.md
Labels: PR: reviewed-approved

#1482 fixed minor writing error, and did the link to the contributors list more intuitive
  README-translated/README-Dutch.md
  README-translated/README-French.md
  README-translated/README-German.md
  README-translated/README-Italian.md
  README-translated/README-Portuguese.md
  README-translated/README-Spanish.md
  README.md
Labels: PR: reviewed-approved, hacktoberfest-accepted

#1651 Enhancing Consistency Chapter with Demo Videos
  book/website/_static/book-stylesheet.css
  book/website/community-handbook/consistency/consistency-formatting.md
  book/website/community-handbook/consistency/consistency-language.md
  book/website/community-handbook/consistency/consistency-structure.md
Labels: PR: unreviewed, gsod2020

#1612 Update GSoD Bi-weekly meeting notes
  communications/GSOD-applications/2020-Paul-Owoicho/check-in.md
Labels: PR: unreviewed, gsod2020

#1673 Final GSoD Report
  communications/GSOD-applications/2020-Paul-Owoicho/README.md
  communications/GSOD-applications/GSoD-2020-Project-Report.md
Labels: PR: unreviewed, gsod2020

#1674 Update README-Korean.md
  README-translated/README-Korean.md
Labels: PR: unreviewed

#1671 Remove redundant bit out and update README-Korean.md
  README-translated/README-Korean.md
  README.md
Labels: PR: reviewed-approved

#1685 Update GSoD-2020-Project-Report.md
  communications/GSOD-applications/GSoD-2020-Project-Report.md
Labels: PR: reviewed-approved

#498 [Ready for Review] Some musings on code styling for reproducibility
  book/website/_toc.yml
  book/website/community-handbook/community-handbook.md
  book/website/figures/console.png
  book/website/figures/lintr_output.png
  book/website/figures/xkcd1285.png
  book/website/figures/zen-of-python.png
  book/website/project-design/code-styling.md
  book/website/project-design/code-styling/code-styling-guidelines.md
  book/website/project-design/code-styling/code-styling-readability.md
  book/website/project-design/code-styling/code-styling-tools.md
  book/website/project-design/filenaming.md
Labels: PR: unreviewed, book-dash-mcr2019, reproducibility-book, software-skills

#1559 The easy way with Github chapter [Ready for review]
  book/website/_toc.yml
  book/website/collaboration/easyway.md
  book/website/collaboration/easyway/sc1_why_learn_how.md
  book/website/collaboration/easyway/sc2_first_steps_on_github.md
  book/website/collaboration/easyway/sc3_using_more_github_features.md
  book/website/collaboration/easyway/sc4_advanced_github_features.md
  book/website/figures/_figure-list.md
  book/website/figures/easyway1_basic_diagram.jpg
  book/website/figures/easyway2_readme_before_edit.jpg
  book/website/figures/easyway3_readme_after_edit.jpg
  book/website/figures/easyway4_edited_readme.jpg
  book/website/figures/easyway5_project.jpg
Labels: PR: reviewed-approved, book-dash-nov20, reproducibility-book

#1686 Add OLS-2 graduation information
  open-life-science-mentoring/README.md
Labels: PR: reviewed-approved

#1689 Update ethics-intro.md to include in the book and add a title
  book/website/_toc.yml
  book/website/ethical-research/ethics-intro.md
Labels: PR: partially-approved

#1691 Novice GitHub image fix and change of fig 42
  book/website/collaboration/github-novice/github-novice-features.md
  book/website/collaboration/github-novice/github-novice-firststeps.md
  book/website/figures/github-project.jpg
  book/website/requirements.txt
Labels: PR: unreviewed, work-in-progress

#1694 added (er)= to top of one .md file
  book/website/ethical-research/ethical-research.md
Labels: PR: reviewed-approved

#1697 Upload an 'EthicalResearch' image and format the figure using MyST
  book/website/ethical-research/ethics-intro.md
  book/website/figures/EthicalResearch.jpg
Labels: PR: reviewed-approved

#1696 Update references.bib with Meyer 2018
  book/website/_bibliography/references.bib
Labels: PR: reviewed-approved
