Repository the-turing-way/the-turing-way, pull requests merged in 2020-04, with the labels that each got.

#1011 [Ready for review] Update issue labels in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#948 figure_list.md: Update missing image names
  book/content/figures/figure_list.md
Labels: PR: partially-approved

#953 Update the opening line of Collaboration cafe doc
  project_management/online-collaboration-cafe.md
Labels: PR: unreviewed, project management

#1018 Cleaning up the contributors table
  .all-contributorsrc
  README.md
Labels: PR: reviewed-approved

#1019 All contribs 20200410
  .all-contributorsrc
Labels: PR: reviewed-approved

#1021 Turn off skipping continuous integration for all contributors bot
  .all-contributorsrc
Labels: PR: reviewed-approved

#1024 (Finally) Add bouweandela & sort alphabetically
  .all-contributorsrc
Labels: PR: reviewed-approved

#1027 removing duplicated Mateusz
  .all-contributorsrc
Labels: PR: reviewed-approved

#1028 Sort all contributors table alphabetically
  .all-contributorsrc
Labels: PR: reviewed-approved

#1035 Add lots of contributors
  .all-contributorsrc
  README.md
Labels: PR: unreviewed

#1036 Create newsletter_13_Apr2020.md
  communications/newsletters/images/cross-Apr2020.png
  communications/newsletters/images/preview-Apr2020.png
  communications/newsletters/images/scriberia-Apr2020.png
  communications/newsletters/images/tweets-Apr2020.png
  communications/newsletters/newsletter_13_Apr2020.md
Labels: PR: unreviewed

#1038 multilingual make uses cached table of contents instead
  book/content/po/toc.yml
  book/website/scripts/multilingual_make.sh
Labels: PR: unreviewed

#714 WIP - Add section on DOIs and ORCIDs to Credit chapter
  book/content/credit/credit.md
Labels: reproducibility-book

#1051 test simple redirect
  book/content/5-book-preview/5-book-preview.md
  book/website/_data/toc.yml
  book/website/_redirects
Labels: PR: unreviewed

#1052 Revert "test simple redirect" - adding more test links for different condition
  book/website/_redirects
Labels: PR: unreviewed

#1012 Add chapter on Open Community Communications
  book/content/open-source-comms/comms-channels.md
  book/content/open-source-comms/further-reading.md
  book/content/open-source-comms/intro.md
  book/content/open-source-comms/issue-tracking.md
  book/website/_data/toc.yml
Labels: PR: partially-approved

#1056 Draft of GSOD 2020 application
  communications/GSOD-applications/2020-gsod.md
Labels: PR: unreviewed

#1058 [Ready for Review] Updating Issue Templates
  .github/ISSUE_TEMPLATE/CHAPTER_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: PR: reviewed-approved, review request

#964 [Ready for Review] Diving into Leadership blog
  book/content/diving_into_leadership/diving_into_leadership.md
  book/website/_data/toc.yml
Labels: PR: unreviewed, review request

#1061 Apply Malvika's review comments to Leadership blog
  book/content/diving_into_leadership/diving_into_leadership.md
Labels: PR: reviewed-approved
