Repository the-turing-way/the-turing-way, pull requests merged in 2020-11, with the labels that each got.

#1523 Update open-resources.md with correct header
  book/website/reproducible-research/open/open-resources.md
Labels: PR: reviewed-approved, book-dash-nov20, bug fixed

#1528 Update open-hardware.md
  book/website/reproducible-research/open/open-hardware.md
Labels: PR: reviewed-approved

#1536 Consistency in ci-checklist.md
  book/website/reproducible-research/ci/ci-checklist.md
Labels: PR: reviewed-approved

#1481 Update CODE_OF_CONDUCT.md reference
  CODE_OF_CONDUCT.md
  book/website/community-handbook/coc/coc-acknowledgement.md
Labels: PR: reviewed-approved

#1538 Review the make.md chapter
  book/website/reproducible-research/make.md
Labels: PR: reviewed-approved

#1306 Documenting Azure credit requests
  project_management/credit_requests/README.md
  project_management/credit_requests/turing_mybinder_azure_credit_request_2019-10.md
  project_management/credit_requests/turing_mybinder_azure_credit_request_2020-08.md
  project_management/credit_requests/turing_mybinder_azure_credit_request_template.md
Labels: PR: partially-approved

#1448 Update licensing-data.md with content created in another branch
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/reproducible-research/licensing.md
  book/website/reproducible-research/licensing/licensing-data.md
Labels: PR: reviewed-approved, gsod2020, hacktoberfest-accepted

#1551 Fix for maintaining consistency in ci-travis.md, issue #1526
  book/website/reproducible-research/ci/ci-travis.md
Labels: PR: reviewed-approved

#1562 Adding a new subchapter on rdm toolkits
  book/website/_toc.yml
  book/website/reproducible-research/rdm/rdm-toolkits.md
Labels: PR: unreviewed, book-dash-nov20, reproducibility-book

#1507 Revised Template for New Chapters
  book/templates/case-study-template.ipynb
  book/templates/chapter-template/README.md
  book/templates/chapter-template/chapter-content/chapter-checklist.md
  book/templates/chapter-template/chapter-content/chapter-content.md
  book/templates/chapter-template/chapter-content/chapter-resources.md
  book/templates/chapter-template/chapter-landing-page.md
  templates/CHAPTER_TEMPLATE.md
Labels: PR: unreviewed, book-dash-nov20, gsod2020, retrospective consistency

#1590 Jessyprovencher master
  README-French.md
Labels: PR: unreviewed

#1591 Update reviewing.md
  book/website/reproducible-research/reviewing.md
Labels: PR: partially-approved

#1570 Update reviewing-workflow.md
  book/website/reproducible-research/reviewing/reviewing-workflow.md
Labels: PR: reviewed-approved, book-dash-nov20

#1569 Update ci-resources.md
  book/website/reproducible-research/ci/ci-resources.md
Labels: PR: reviewed-approved, book-dash-nov20

#1564 Improve consistency in make chapter
  book/website/_toc.yml
  book/website/reproducible-research/make.md
  book/website/reproducible-research/make/make-appendix.md
  book/website/reproducible-research/make/make-casestudy.md
  book/website/reproducible-research/make/make-debugging.md
  book/website/reproducible-research/make/make-examples.md
  book/website/reproducible-research/make/make-resources.md
  book/website/reproducible-research/make/make-results.md
Labels: PR: reviewed-approved, book-dash-nov20

#1556 Update reviewing-checklist.md
  book/website/reproducible-research/reviewing/reviewing-checklist.md
Labels: PR: reviewed-approved, book-dash-nov20

#1568 Update compendia.md
  book/website/reproducible-research/compendia.md
Labels: PR: partially-approved, book-dash-nov20

#1539 Reviewed credit.md chapter
  book/website/reproducible-research/credit.md
Labels: PR: partially-approved, book-dash-nov20

#1589 first update of glossary
  book/website/afterword/glossary.md
Labels: book-dash-nov20, ready for merge

#1598 Update the Current Set of Issue Templates
  .github/ISSUE_TEMPLATE/CHAPTER_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: PR: reviewed-approved, gsod2020

#1580 Update list with new bibliography from intro to Guide for Ethical Research references.bib
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/ethical-research/preclinical-research.md
  book/website/reproducible-research/licensing/licensing-checklist.md
  book/website/reproducible-research/licensing/licensing-data.md
  book/website/reproducible-research/rdm/rdm-sharing.md
Labels: PR: reviewed-approved, book-dash-nov20

#1468 Add first Version of German README
  README-translated/README-German.md
  README.md
Labels: PR: unreviewed, hacktoberfest-accepted

#1522 Updated vcs-resources.md
  book/website/reproducible-research/vcs/vcs-data.md
  book/website/reproducible-research/vcs/vcs-resources.md
Labels: PR: unreviewed, book-dash-nov20

#1604 Update .all-contributorsrc for a minor JSON error and move French README to README-translated
  .all-contributorsrc
  README-translated/README-French.md
Labels: PR: reviewed-approved

#1600 Clarify bibliography page
  book/website/community-handbook/style/style-citing.md
Labels: PR: reviewed-approved

#1601 Update Chapter template with template for Personal Stories
  book/templates/chapter-template/README.md
  book/templates/chapter-template/chapter-content/chapter-content.md
  book/templates/chapter-template/chapter-content/chapter-personal-stories.md
  book/templates/chapter-template/chapter-landing-page.md
Labels: PR: unreviewed, gsod2020

#1561 Upgrade Jupyter Book / Enable collaborative annotation in the book
  book/website/_config.yml
  book/website/_static/myfile.css
  book/website/requirements.txt
Labels: PR: reviewed-approved, book-dash-nov20

#1459 Chapter on maintaining consistency in The Turing Way chapters
  book/website/_toc.yml
  book/website/community-handbook/consistency.md
  book/website/community-handbook/consistency/consistency-formatting.md
  book/website/community-handbook/consistency/consistency-language.md
  book/website/community-handbook/consistency/consistency-structure.md
  book/website/community-handbook/style/style-citing.md
  book/website/community-handbook/style/style-figures.md
  book/website/figures/checklist-formatting.png
  book/website/figures/empty_toc_file.png
  book/website/figures/html_to_markdown.png
  book/website/figures/html_to_markdown2.png
  book/website/figures/many_table_of_contents.png
  book/website/figures/mismatched_title_toc.png
  book/website/figures/recommended_chapter_structure.png
Labels: PR: unreviewed, book-dash-nov20, gsod2020, hacktoberfest-accepted

#1611 Fix broken Relative Links in Chapter and Case Study templates
  book/templates/case-study-template/case-study-template.md
  book/templates/chapter-template/README.md
Labels: PR: reviewed-approved, gsod2020

#1613 Typos and Definition addition
  book/website/afterword/glossary.md
Labels: PR: unreviewed

#1620 Update Content Templates section of README
  book/README.md
Labels: PR: unreviewed, gsod2020

#1621 Update label for Communications guide
  book/website/community-handbook/style/style-crossref.md
Labels: PR: reviewed-approved, gsod2020

#1624 Format glossary with JupyterBook standard
  book/website/_toc.yml
  book/website/afterword/afterword.md
  book/website/afterword/glossary.md
  book/website/community-handbook/acknowledgement/acknowledgement-members.md
  book/website/community-handbook/style/style-more-styling.md
  book/website/reproducible-research/binderhub/binderhub-build.md
Labels: PR: reviewed-approved

#1567 Refactoring and adding Remote collaboration chapter from old PRs
  book/website/_toc.yml
  book/website/collaboration/leadership.md
  book/website/collaboration/new-community.md
  book/website/collaboration/remote-collab.md
  book/website/collaboration/remote-collab/remote-collab-chairs.md
  book/website/collaboration/remote-collab/remote-collab-conferences.md
  book/website/collaboration/remote-collab/remote-collab-coworking.md
  book/website/collaboration/remote-collab/remote-collab-guidelines.md
  book/website/collaboration/remote-collab/remote-collab-informal.md
  book/website/collaboration/remote-collab/remote-collab-management.md
  book/website/collaboration/remote-collab/remote-collab-meetings.md
  book/website/collaboration/remote-collab/remote-collab-participation.md
  book/website/collaboration/remote-collab/remote-collab-prosandcons.md
  book/website/collaboration/remote-collab/remote-collab-tools.md
  book/website/figures/distributed-collaboration.jpg
Labels: PR: unreviewed, book-dash-nov20, collaboration-book

#1625 Change link from preprint to paper
  book/website/_bibliography/references.bib
  book/website/reproducible-research/renv/renv-resources.md
Labels: PR: unreviewed

#1622 Update compendia.md
  book/website/reproducible-research/compendia.md
Labels: PR: unreviewed

#1623 Update CI to check multiple OSs and Python versions
  .github/workflows/ci.yml
Labels: PR: partially-approved

#1648 Added a link to the new chapter template to the contribution guides.
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#1466 Retrospective consistency for Open Research Chapter of the Guide to Reproducible Research
  book/website/_toc.yml
  book/website/reproducible-research/open.md
  book/website/reproducible-research/open/open-access.md
  book/website/reproducible-research/open/open-checklist.md
  book/website/reproducible-research/open/open-data.md
  book/website/reproducible-research/open/open-hardware.md
  book/website/reproducible-research/open/open-notebooks.md
  book/website/reproducible-research/open/open-resources.md
  book/website/reproducible-research/open/open-scholarship.md
  book/website/reproducible-research/open/open-source.md
Labels: PR: reviewed-approved, gsod2020, hacktoberfest-accepted

#1652 Fixing 89 typos
  book/.words.lst
  book/README.md
  book/templates/case-study-template/case-study-template.md
  book/templates/chapter-template/chapter-content/chapter-personal-stories.md
  book/website/LICENSE.md
  book/website/_bibliography/references.bib
  book/website/afterword/bibliography.md
  book/website/afterword/contributors-record.md
  book/website/collaboration/remote-collab/remote-collab-tools.md
  book/website/communication/os-comms.md
  book/website/communication/os-comms/os-comms-channels.md
  book/website/communication/os-comms/os-comms-issue-tracking.md
  book/website/community-handbook/bookdash/bookdash-events.md
  book/website/community-handbook/community-handbook.md
  book/website/community-handbook/consistency.md
  book/website/community-handbook/consistency/consistency-structure.md
  book/website/community-handbook/style.md
  book/website/community-handbook/style/style-citing.md
  book/website/community-handbook/style/style-crossref.md
  book/website/community-handbook/style/style-figures.md
  book/website/figures/_figure-list.md
  book/website/reproducible-research/case-studies/statistical-methods-manuscript.md
  book/website/reproducible-research/ci/ci-resources.md
  book/website/reproducible-research/ci/ci-travis.md
  book/website/reproducible-research/code-quality/code-quality-resources.md
  book/website/reproducible-research/code-quality/code-quality-style.md
  book/website/reproducible-research/credit.md
  book/website/reproducible-research/licensing/licensing-software.md
  book/website/reproducible-research/open.md
  book/website/reproducible-research/overview/overview-benefit.md
  book/website/reproducible-research/overview/overview-definitions.md
  book/website/reproducible-research/renv/renv-binder.md
  book/website/reproducible-research/renv/renv-containers.md
  book/website/reproducible-research/renv/renv-vm.md
  book/website/reproducible-research/renv/renv-yaml.md
  book/website/reproducible-research/reviewing.md
  book/website/reproducible-research/testing/testing-resources.md
  book/website/reproducible-research/testing/testing-types.md
  book/website/reproducible-research/vcs/vcs-github.md
  contributors.md
Labels: PR: unreviewed

#1547 Consistent formatting in project-design/filenaming.md
  book/website/project-design/filenaming.md
Labels: PR: reviewed-approved, book-dash-nov20

#1655 ✏️ Fix a typo in TOC
  book/website/_toc.yml
Labels: PR: partially-approved

#1654 Fix typos
  README-translated/README-Korean.md
  book_skeleton.md
Labels: PR: reviewed-approved

#1650 Create README-Korean.md
  README-translated/README-Korean.md
Labels: PR: reviewed-changes-requested

#1574 Feedback on "getting started with GitHub" chapter
  book/website/collaboration/easyway/sc1_why_learn_how.md
Labels: PR: unreviewed, book-dash-nov20

#1647 Update reviewing-motivation.md
  book/website/ethical-research/ethical-research.md
  book/website/reproducible-research/code-quality/code-quality-style.md
  book/website/reproducible-research/reviewing/reviewing-motivation.md
Labels: PR: reviewed-approved, gsod2020

#1320 Update the reviewing chapter
  book/website/reproducible-research/code-quality.md
  book/website/reproducible-research/reviewing.md
  book/website/reproducible-research/reviewing/reviewing-checklist.md
  book/website/reproducible-research/reviewing/reviewing-motivation.md
  book/website/reproducible-research/reviewing/reviewing-recommend.md
  book/website/reproducible-research/reviewing/reviewing-resources.md
  book/website/reproducible-research/reviewing/reviewing-workflow.md
Labels: PR: unreviewed, book-dash-nov20

#1656 Adjusting the look of Tables across the entire Book
  book/website/_static/book-stylesheet.css
  book/website/_static/myfile.css
  book/website/community-handbook/consistency/consistency-formatting.md
  book/website/reproducible-research/licensing/licensing-software.md
Labels: PR: partially-approved, gsod2020
