Repository the-turing-way/the-turing-way, pull requests merged in 2020-03, with the labels that each got.

#903 [Ready for review] Update RDM
  book/content/rdm/rdm.md
Labels: PR: unreviewed, book-dash-feb20

#930 Change pages footer to link to Turing Way contributors
  book/website/_config.yml
Labels: PR: reviewed-approved

#926 Formatting the introduction chapter
  book/content/reproducibility/reproducibility.md
Labels: PR: reviewed-approved

#931 fixed typo
  book/content/risk_assessment/01/longreadriskassessment.md
Labels: PR: unreviewed

#904 [Ready for review] Chapter on naming
  book/content/naming/naming.md
Labels: PR: unreviewed, book-dash-feb20

#840 [Ready for review] New chapter: Research compendia
  book/content/figures/ResearchCompendium.jpg
  book/content/open_research/01/opendata.md
  book/content/research_compendia/research_compendia.md
  book/website/_bibliography/references.bib
  book/website/_data/toc.yml
Labels: PR: unreviewed, book-dash-feb20

#837 [Ready for review] Improve open data chapter, links to rdm (see #835)
  book/content/open_research/01/opendata.md
Labels: book-dash-feb20, good first issue, research-related-theory

#949 [MRG] Add April dates for collaboration cafe
  project_management/online-collaboration-cafe.md
Labels: PR: reviewed-approved

#955 Create newsletter_12_Mar2020.md
  communications/newsletters/images/100min-relay-Mar2020.png
  communications/newsletters/images/Tweet-combo-Mar2020.png
  communications/newsletters/images/book-dash-Mar2020.png
  communications/newsletters/images/collab-cafe-Mar2020.png
  communications/newsletters/images/research-compendia-Mar2020.png
  communications/newsletters/newsletter_12_Mar2020.md
Labels: PR: unreviewed

#951 Fix some typos for research compendia
  book/content/research_compendia/research_compendia.md
Labels: PR: reviewed-approved

#968 Fix small typo
  book/content/introduction/introduction.md
Labels: PR: reviewed-approved

#971 fixed typos, improved some wording
  book/content/remote_collaboration/checklist/checklist.md
Labels: PR: unreviewed

#976 add s
  book/content/remote_collaboration/checklist/checklist.md
Labels: PR: unreviewed

#880 Add Choose a license docs from NLeSC guide
  book/content/figures/license_examples/xtas_all_python_libs_96.svg.png
  book/content/figures/license_examples/xtas_chardet_96.svg.png
  book/content/figures/license_examples/xtas_corenlp_1_96.svg.png
  book/content/figures/license_examples/xtas_corenlp_2_96.svg.png
  book/content/figures/license_examples/xtas_overview_96.svg.png
  book/content/figures/license_examples/xtas_snowball_96.svg.png
  book/content/figures/license_examples/xtas_unidecode_96.svg.png
  book/content/licensing/01/softwarelicenses.md
  book/content/licensing/02/datalicenses.md
  book/content/licensing/licensing.md
  book/content/open_research/02/opensourcesoftware.md
  book/content/open_research/07/resources.md
  book/content/version_control/version_control.md
  book/website/_data/toc.yml
Labels: PR: unreviewed, book-dash-feb20

#759 WIP: Restructuring the Research Data Management chapter
  book/content/rdm/docmetadata.md
  book/content/rdm/fairprinciples.md
  book/content/rdm/personalstories.md
  book/content/rdm/rdm.md
  book/content/rdm/resources.md
  book/content/rdm/sharingarchiving.md
  book/content/rdm/spreadsheets.md
  book/content/rdm/storagebackup.md
  book/website/_data/toc.yml
Labels: review request

#982 Add "et cetera" as a deprecated Latinism
  tests/no-bad-latin.py
Labels: PR: reviewed-approved

#978 Remove i.e. from the license chapter
  book/content/licensing/01/softwarelicenses.md
Labels: PR: reviewed-approved, reproducibility-book

#979 link for rdm and license corrected
  book/website/_data/toc.yml
Labels: PR: reviewed-approved

#891 [Ready to review] Edit section on open source hardware
  book/content/ethics/ethics.md
  book/content/open_research/03/openhardware.md
Labels: PR: unreviewed, book-dash-feb20, review request

#961 Update zero to binder tutorial (python)
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-solo.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder.md
Labels: PR: reviewed-approved, review request

#981 [MRG] Add table of test status badges to README
  README.md
Labels: PR: unreviewed

#980 [MRG] Remove bad latin phrases so CI passes
  book/content/credit/credit.md
  book/content/licensing/01/softwarelicenses.md
  book/content/rdm/fairprinciples.md
  book/content/rdm/sharingarchiving.md
Labels: PR: reviewed-approved, typo-fix

#902 Adding Data and software citation to credit.md
  book/content/credit/credit.md
Labels: PR: unreviewed, book-dash-feb20

#984 Removed redundancy from the rdm split chapters
  book/content/credit/credit.md
  book/content/ethics/ethics.md
  book/content/rdm/docmetadata.md
  book/content/rdm/fairprinciples.md
  book/content/rdm/personalstories.md
  book/content/rdm/rdm.md
  book/content/rdm/resources.md
  book/content/rdm/sharingarchiving.md
  book/content/rdm/spreadsheets.md
  book/content/rdm/storagebackup.md
Labels: PR: reviewed-approved, reproducibility-book, review request

#906 [Ready for review] Shorten 'Make your data citeable' in opendata.md
  book/content/open_research/01/opendata.md
Labels: PR: unreviewed, approval request, book-dash-feb20

#987 [Ready for Review] Correct issues in all-contributorsrc file
  .all-contributorsrc
Labels: PR: reviewed-approved, approval request, bug fixed

#986 Light edit
  book/content/credit/credit.md
  book/content/introduction/introduction.md
  book/content/reproducibility/01/importantforscience.md
  book/content/reproducibility/02/whycare.md
  book/content/reproducibility/03/definitions.md
Labels: PR: reviewed-approved

#898 Add code quality chapter
  book/content/code_quality/code_quality.md
  book/content/reviewing/01/how_helpful.md
  book/content/reviewing/03/typical_workflows.md
  book/content/testing/testing.md
  book/content/version_control/version_control.md
  book/website/_data/toc.yml
Labels: PR: reviewed-approved, book-dash-feb20, review request

#990 toc.yml updated to add '/'
  book/website/_data/toc.yml
Labels: PR: reviewed-approved, book-build, review request
