Repository the-turing-way/the-turing-way, pull requests merged in 2020-08, with the labels that each got.

#1283 Minor update for rdm-spreadsheets.md
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
Labels: PR: reviewed-approved

#1282 Create promotion pack for external representation of the community
  communications/promotion-pack/README.md
  communications/promotion-pack/faqs.md
Labels: PR: unreviewed, community

#1280 Add abstracts for conferences in 2020
  conferences/abstracts/2020-03-DataSciencePerspectivesConference.md
  conferences/abstracts/2020-04-CW20.md
  conferences/abstracts/2020-05-WiDS-IBM.md
  conferences/abstracts/2020-06-CogX.md
  conferences/abstracts/2020-06-TPS-OLS2-for-Turing.md
  conferences/abstracts/2020-07-EANBiT-icipe.md
  conferences/abstracts/2020-07-MIT-Experiential-Ethics.md
  conferences/abstracts/2020-07-Scipy.md
  conferences/abstracts/2020-08-CarpentryCon-at-home-lightning.md
  conferences/abstracts/2020-09-JupyterCon-sprint.md
  conferences/abstracts/2020-10-JupyterCon-tutorial.md
  conferences/abstracts/2020-11-Biohackathon-EU.md
Labels: PR: reviewed-approved, approval request

#1288 Update rdm-spreadsheets.md
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
Labels: PR: unreviewed

#1289 minor update in number of current contributors
  communications/promotion-pack/README.md
Labels: PR: unreviewed, good first PR review

#1268 Update CONTRIBUTING.md file with new changes, link out to the style guide in handbook
  CONTRIBUTING.md
  conferences/README.md
  conferences/abstracts/2020-06-TPS-OLS2-for-Turing.md
Labels: PR: unreviewed, community, enhancement

#1299 Correct Zero to Binder link in the workshop agenda, and abstract links in conference table
  conferences/README.md
  workshops/boost-research-reproducibility-binder/agenda.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/ReproducibleComputationalEnvironment_compressed.pdf
  workshops/boost-research-reproducibility-binder/workshop-presentations/TuringWay-BinderJune_compressed.pdf
Labels: PR: unreviewed

#1292 update relative link for rdm-metadata.md
  book/website/reproducible-research/rdm/rdm-metadata.md
Labels: PR: reviewed-approved, reproducibility-book

#1301 Update README.md
  conferences/README.md
Labels: PR: reviewed-approved

#1304 Fix PR-based CI to account for files that have been deleted
  tests/lorem-ipsums.py
  tests/no-bad-latin.py
Labels: PR: unreviewed

#1302 Style guide update: remove table for cross ref labels
  book/website/community-handbook/style/style-crossref.md
  book/website/crossref/labels.md
Labels: PR: unreviewed

#1308 Minor rewording suggestions
  book/website/community-handbook/newsletters.md
Labels: PR: reviewed-approved

#1257 A new chapter on The Turing Way coworking calls (for the community handbook)
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/community-handbook/community-handbook.md
  book/website/community-handbook/community-templates.md
  book/website/community-handbook/coworking.md
  book/website/community-handbook/coworking/coworking-collabcafe.md
  book/website/community-handbook/coworking/coworking-motivation.md
  book/website/community-handbook/coworking/coworking-organisation.md
  book/website/community-handbook/coworking/coworking-weekly.md
  book/website/community-handbook/templates/coworking-collabcafe-template.md
  book/website/community-handbook/templates/coworking-weekly-template.md
  book/website/figures/coworking.png
  book/website/figures/templates.png
Labels: PR: unreviewed, community-handbook, review request

#1262 Create a chapter on Book Dash (for the community handbook)
  book/website/_toc.yml
  book/website/community-handbook/bookdash.md
  book/website/community-handbook/bookdash/bookdash-application.md
  book/website/community-handbook/bookdash/bookdash-events.md
  book/website/community-handbook/bookdash/bookdash-preparation.md
  book/website/community-handbook/community-templates.md
  book/website/community-handbook/coworking/coworking-organisation.md
  book/website/community-handbook/newsletters/newsletters-process.md
  book/website/community-handbook/templates/bookdash-feedback-template.md
  book/website/community-handbook/templates/bookdash-issue-template.md
  book/website/community-handbook/templates/bookdash-notes-template.md
  book/website/community-handbook/templates/bookdash-precall-template.md
  book/website/figures/bookdash.png
Labels: PR: partially-approved, community-handbook, review request

#1121 Acknowledgement chapter for The Turing Way handbook
  GOVERNANCE.md
  book/website/_config.yml
  book/website/_toc.yml
  book/website/afterword/afterword.md
  book/website/afterword/contributors-record.md
  book/website/community-handbook/acknowledgement.md
  book/website/community-handbook/acknowledgement/acknowledgement-examples.md
  book/website/community-handbook/acknowledgement/acknowledgement-members.md
  book/website/community-handbook/acknowledgement/acknowledgement-record.md
  book/website/community-handbook/bookdash.md
  book/website/community-handbook/bookdash/bookdash-application.md
  book/website/community-handbook/bookdash/bookdash-events.md
  book/website/community-handbook/bookdash/bookdash-preparation.md
  book/website/community-handbook/coworking/coworking-collabcafe.md
  book/website/community-handbook/coworking/coworking-weekly.md
  book/website/community-handbook/style/style-citing.md
  book/website/community-handbook/style/style-crossref.md
  book/website/community-handbook/style/style-figures.md
  book/website/community-handbook/templates.md
  book/website/community-handbook/templates/template-bookdash-feedback.md
  book/website/community-handbook/templates/template-bookdash-issue.md
  book/website/community-handbook/templates/template-bookdash-notes.md
  book/website/community-handbook/templates/template-bookdash-precall.md
  book/website/community-handbook/templates/template-coworking-collabcafe.md
  book/website/community-handbook/templates/template-coworking-weekly.md
  book/website/figures/ThatCouldBeAChapter.png
  book/website/figures/_figure-list.md
  book/website/figures/allcontributorsbot-emoji.png
  contributors.md
  helper-scripts/contributors.sh
  project_management/personas.md
  tests/no-bad-latin.py
Labels: PR: unreviewed, community

#1311 Hold acknowledgement chapters for review
  book/website/_toc.yml
Labels: PR: reviewed-approved
