Repository the-turing-way/the-turing-way, pull requests merged in 2020-06, with the labels that each got.

#1184 Open Research: Fix broken links
  book/website/open_research/01/opendata.md
  book/website/open_research/open_research.md
Labels: PR: reviewed-approved

#1186 Editing and adding content in the code quality chapter
  book/website/code_quality/code_quality.md
  book/website/version_control/vcs-checklist.md
Labels: PR: partially-approved

#1199 Add labels and cross-references
  book/website/reproducible-research/overview.md
  book/website/reproducible-research/overview/overview-benefit.md
  book/website/reproducible-research/overview/overview-definitions.md
  book/website/reproducible-research/overview/overview-resources.md
Labels: PR: unreviewed

#1202 Add labels to chapters, cross-reference those from inside different chapter
  book/website/reproducible-research/open.md
  book/website/reproducible-research/overview/overview-benefit.md
  book/website/reproducible-research/overview/overview-resources.md
  book/website/reproducible-research/reproducible-research.md
  book/website/reproducible-research/vcs.md
Labels: PR: reviewed-approved

#1201 Add conditional html proofer
  .github/workflows/ci.yml
Labels: PR: reviewed-approved

#1203 Explain style convention for labels and cross-references
  book/website/community-handbook/style/style-crossref.md
  book/website/reproducible-research/overview/overview-resources.md
Labels: PR: unreviewed

#1142 Fix typos
  .github/ISSUE_TEMPLATE/bug_report.md
  book/website/Ethical_Decisions/Planning_Research.md
  book/website/open-source-comms/comms-channels.md
  book/website/open_research/01/opendata.md
  book/website/rdm/storagebackup.md
  book/website/reproducible_environments/02/package-management.md
  book/website/reproducible_environments/06/containers.md
  book/website/version_control/version_control.md
  project_management/personas.md
Labels: PR: unreviewed

#1204 Fix labels for Code of Conduct subchapter
  book/website/community-handbook/coc.md
  book/website/community-handbook/coc/coc-details.md
  book/website/community-handbook/coc/coc-enforcement.md
  book/website/community-handbook/coc/coc-reporting.md
Labels: PR: unreviewed

#1206 Update ethical-research.md
  book/website/ethical-research/ethical-research.md
Labels: PR: unreviewed

#1207 Update ethical-research.md section
  book/website/ethical-research/ethical-research.md
Labels: PR: reviewed-approved

#1208 Update _toc.yml to remove inconsistent hear/title in the book
  book/website/_toc.yml
Labels: PR: reviewed-approved

#985 [Ready for Review] Refining CI tests: Run test on changed files in PR
  .github/workflows/lorem-ipsums.yml
  .github/workflows/no-bad-latin.yml
  .gitignore
  README.md
  tests/lorem-ipsums.py
  tests/no-bad-latin.py
  tests/pull_files.py
  tests/requirements.txt
Labels: PR: unreviewed

#1211 Bugfix: Fix team photo in readme
  README.md
Labels: PR: reviewed-approved, bug fixed

#1212 Bugfix: Add an ignore list to no-bad-latin.py
  README.md
  tests/no-bad-latin.py
Labels: PR: reviewed-approved, bug

#1213 rename the CI chapters correctly
  book/website/_toc.yml
  netlify.toml
  tests/no-bad-latin.py
Labels: PR: reviewed-approved

#1128 Personas: Git log statement is added to the bottom
  project_management/personas.md
Labels: PR: unreviewed

#1216 [Ready for Review] Fix a bug in our tests
  tests/no-bad-latin.py
Labels: PR: reviewed-approved, approval request, bug fixed

#1198 [Ready for Review] Tidy up the Python and R Binder tutorials
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-r.md
Labels: PR: partially-approved

#1209 Fix anchor links in Make example
  book/website/reproducible-research/make.md
  book/website/reproducible-research/make/make-casestudy.md
  book/website/reproducible-research/make/make-examples.md
  book/website/reproducible-research/make/make-resources.md
Labels: PR: unreviewed

#1219 Changes from List of continuous integration services #1070
  book/website/_toc.yml
  book/website/reproducible-research/ci/ci-options.md
  book/website/reproducible-research/ci/ci-travis.md
Labels: PR: reviewed-approved

#959 [Ready for Review] Translate Zero-to-Binder tutorial into Julia
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-julia.md
Labels: PR: reviewed-approved

#1222 Adding newsletter_15_June2020.md draft on GitHub
  communications/newsletters/images/BLM-June2020.png
  communications/newsletters/images/OLS-June2020.png
  communications/newsletters/images/TPS-June2020.png
  communications/newsletters/images/TW-June2020.png
  communications/newsletters/images/binder-June2020.png
  communications/newsletters/images/datafem-June2020.png
  communications/newsletters/images/riots-June2020.png
  communications/newsletters/images/tweets-June2020.png
  communications/newsletters/newsletter_15_June2020.md
Labels: PR: reviewed-approved

#1189 [Ready-for-Review]Create new subchapter for reviewing PRs and maintainance for GitHub collaboration
  book/website/_toc.yml
  book/website/collaboration/github/github-contributors.md
  book/website/collaboration/github/github-maintainers.md
  book/website/collaboration/github/github-readme.md
  book/website/collaboration/github/github-roadmapping.md
Labels: PR: reviewed-approved

#1223 A first idea on how to guide people to represent TTW
  CONTRIBUTING.md
Labels: PR: reviewed-approved
