Repository the-turing-way/the-turing-way, pull requests merged in 2020-07, with the labels that each got.

#1245 [Ready for Review] Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#1252 A persona chapter in the Project design file
  book/website/_toc.yml
  book/website/figures/persona-creation.png
  book/website/project-design/persona-creation.md
Labels: PR: unreviewed, project-design-book, review request

#1258 Update persona-creation chapter with minor update
  book/website/project-design/persona-creation.md
Labels: PR: unreviewed, enhancement, project-design-book

#1248 [Ready for Review] add case studies chapter for RR
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/reproducible-research/binderhub.md
  book/website/reproducible-research/case-studies.md
  book/website/reproducible-research/case-studies/statistical-methods-manuscript.md
  book/website/reproducible-research/ci.md
  book/website/reproducible-research/ci/ci-travis.md
  book/website/reproducible-research/credit.md
  book/website/reproducible-research/rdm.md
  book/website/reproducible-research/renv/renv-binder.md
  book/website/reproducible-research/renv/renv-containers.md
  book/website/reproducible-research/reproducible-research.md
  tests/no-bad-latin.py
Labels: PR: unreviewed

#1259 remove latin words from the CoC to stop CI from complaining
  book/website/community-handbook/coc/coc-enforcement.md
Labels: PR: reviewed-approved

#1260 [Ready for Review] fix python package requirements
  book/website/requirements.txt
Labels: PR: reviewed-approved

#1261 super minor update in the bibliography
  book/website/_bibliography/references.bib
Labels: PR: reviewed-approved, approval request

#1241 Tiny typo fix
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#1266 Minor mistake in code-quality.md
  book/website/reproducible-research/code-quality.md
Labels: PR: reviewed-approved

#1263 Draft for the newsletter for July 2020
  communications/newsletters/images/IsmaelEthics-July2020.png
  communications/newsletters/images/MartinaContributor-July2020.png
  communications/newsletters/images/ReviewScriberia-July2020.png
  communications/newsletters/images/Tweets-July2020.png
  communications/newsletters/images/distributed-July2020.png
  communications/newsletters/newsletter_13_Apr2020.md
  communications/newsletters/newsletter_16_July2020.md
Labels: PR: unreviewed, community, review request

#1232 Edit open-source software benefits for research
  book/website/reproducible-research/open/open-source.md
Labels: PR: unreviewed

#1274 Update .all-contributorsrc to add the missing ']'
  .all-contributorsrc
Labels: PR: reviewed-approved

#1250 [Ready to review] Update rdm-spreadsheets.md
  book/website/figures/tidy-1.png
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
Labels: PR: unreviewed, enhancement, review request

#1277 Fix 'open_access_citations' image rendering
  book/website/figures/_figure-list.md
  book/website/figures/open_access_citations.jpg
  book/website/reproducible-research/open.md
Labels: PR: unreviewed
