Repository the-turing-way/the-turing-way, pull requests merged in 2020-05, with the labels that each got.

#1042 Update storage.md
  book/content/rdm/storagebackup.md
Labels: PR: unreviewed

#1060 Ci chapter
  book/content/continuous_integration/continuous_integration.md
Labels: PR: reviewed-approved

#1064 Fixing broken link https://git-scm.com/docs/git-request-pull
  book/content/version_control/version_control.md
Labels: PR: reviewed-approved

#881 Mention how to install build requirements
  CONTRIBUTING.md
Labels: PR: unreviewed, book-dash-feb20, community

#1057 Revert "Draft of GSOD 2020 application"
  2020-gsod.md
  communications/GSOD-applications/2020-gsod.md
  communications/GSOD-applications/GSoD2020-TheTuringWay.pdf
Labels: PR: unreviewed, ready for merge

#1071 Added citations for 2.1
  book/content/reproducibility/01/importantforscience.md
  book/website/_bibliography/references.bib
Labels: PR: reviewed-approved

#1067 [Ready for Review] Add welcome bot
  .github/config.yml
  README.md
Labels: PR: unreviewed, community

#1074 Add "I want to contribute" badge to README
  README.md
Labels: PR: unreviewed

#1081 expand abbreviation of HPC in the containers section
  book/content/reproducible_environments/06/containers.md
Labels: PR: reviewed-approved

#1084 Typo and Link Fix
  book/content/open_research/01/opendata.md
Labels: PR: reviewed-approved

#1080 Fixes #1016 - remove referece to non-existent file from CONTRIBUTING.
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#1088 Added community_profile.png and fixed the broken link
  book/content/collaborating_github/4/checklist_bibliography.md
  book/content/figures/community_profile.png
Labels: PR: reviewed-approved

#1091 Added ISSUE_TEMPLATE link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR: unreviewed

#1096 Update resources.md
  book/content/reproducibility/04/resources.md
Labels: PR: reviewed-approved

#1077 Improve research compendia Chapter : Fixed Broken Links
  book/content/research_compendia/research_compendia.md
Labels: PR: reviewed-approved

#1108 Draft for the May's Newsletter in the filename: newsletter_14_May2020.md
  communications/newsletters/images/kw-May2020.png
  communications/newsletters/images/mhaw-May2020.png
  communications/newsletters/images/ra-May2020.png
  communications/newsletters/images/rh-May2020.png
  communications/newsletters/images/tweets-May2020.png
  communications/newsletters/newsletter_14_May2020.md
Labels: PR: unreviewed

#1117 correcting search box text
  book/website/assets/html/search_form.html
Labels: PR: reviewed-approved, book-build

#1120 update emoji key reference
  README.md
Labels: PR: reviewed-approved

#1119 fixing md formatting in contributing file
  CONTRIBUTING.md
Labels: PR: reviewed-approved, typo-fix

#470 [Ready for review] Add contributor personas & pathways
  project_management/personas.md
Labels: PR: unreviewed, project management

#1123 fix broken links in CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: partially-approved, good first PR review

#859 Restructure version control chapter and add subchapter on VCS for data
  book/content/figures/Provenance.jpg
  book/content/figures/github-account.png
  book/content/figures/github-files.png
  book/content/figures/github-readme.png
  book/content/figures/github-repo.png
  book/content/version_control/vcs-checklist.md
  book/content/version_control/vcs-data.md
  book/content/version_control/vcs-git-branches.md
  book/content/version_control/vcs-git-commit.md
  book/content/version_control/vcs-git-compare.md
  book/content/version_control/vcs-git-merge.md
  book/content/version_control/vcs-git-summary.md
  book/content/version_control/vcs-git.md
  book/content/version_control/vcs-github.md
  book/content/version_control/vcs-personal-stories.md
  book/content/version_control/vcs-workflow.md
  book/content/version_control/version-control.md
  book/content/version_control/version_control.md
  book/website/_data/toc.yml
Labels: PR: unreviewed, book-dash-feb20

#1171 Comment out the html proofer
  .github/workflows/ci.yml
  book/README.md
Labels: PR: unreviewed

#1132 Add citation to the computational environments chapter
  book/website/_bibliography/references.bib
  book/website/reproducible_environments/08/resources.md
Labels: PR: unreviewed

#1179 Create EDITOR_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/EDITOR_ISSUE_TEMPLATE.md
Labels: PR: unreviewed
