Repository the-turing-way/the-turing-way, pull requests merged in 2020-02, with the labels that each got.

#809 Fix typo in licence
  LICENSE.md
Labels: bug fixed

#781 fix CI typos
  book/content/continuous_integration/continuous_integration.md
Labels: review request

#541 Add Louise's impact statement
  project_management/impact_statements/louise-bowler.md
Labels: project management

#547 [Ready for Review] Add Sarah's impact statement
  project_management/impact_statements/quotes/quote_betatim.png
  project_management/impact_statements/quotes/quote_choldgraf.png
  project_management/impact_statements/quotes/quote_ggorman.png
  project_management/impact_statements/sarah-gibson.md
Labels: project management

#704 Add barrier 6 (takes time) to barriers.md in reproducibility chapter
  book/content/reproducibility/04/barriers.md
Labels: book

#822 [WIP] Report for Binder workshop at British Antarctic Survey
  workshops/boost-research-reproducibility-binder/agenda.md
  workshops/boost-research-reproducibility-binder/reports/workshop_report_20190301-and-12.md
  workshops/boost-research-reproducibility-binder/reports/workshop_report_20200131.md
  workshops/boost-research-reproducibility-binder/reports/workshop_report_template.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/IntroBoostResReproBinder_20200131.pdf
  workshops/boost-research-reproducibility-binder/workshop-presentations/ReproducibleComputationalEnvironment_20190626.pdf
  workshops/boost-research-reproducibility-binder/workshop-presentations/ReproducibleComputationalEnvironment_20200131.pdf
Labels: community, events

#801 Updated Collaboration Cafe table for 2020
  project_management/online-collaboration-cafe.md
Labels: approval request

#833 Add participant feedback to workshop report
  workshops/boost-research-reproducibility-binder/feedback/workshop_feedback_Cambridge_20200131.csv
  workshops/boost-research-reproducibility-binder/reports/workshop_report_20200131.md
Labels: community, events

#819 Add credit request for Turing BinderHub
  project_management/turing_binderhub_azure_credit_request_Oct2019.md
Labels: binderhub, review request

#830 Newsletter for Feb 2020
  communications/newsletters/images/BAS-Binder-workshop-picture.jpg
  communications/newsletters/images/FairCookbook-Feb2020.png
  communications/newsletters/images/Malvika-softwarecarpentry-Feb2020.png
  communications/newsletters/images/OpenMRBenelux-BrainCookies.jpeg
  communications/newsletters/images/PyDataCambridge-Sarah-Feb2020.jpg
  communications/newsletters/images/Tweet-Translation-Feb2020.png
  communications/newsletters/images/Tweet-combo-Feb2020.jpg
  communications/newsletters/images/Twitterbio-TuringWay-Feb2020.png
  communications/newsletters/newsletter_11_Feb2020.md
Labels: comms, community

#762 [WIP] Update BinderHub workshop
  workshops/build-a-binderhub/binderhub_resources/activity_log1.png
  workshops/build-a-binderhub/binderhub_resources/activity_log2.png
  workshops/build-a-binderhub/binderhub_resources/github_oauth.png
  workshops/build-a-binderhub/binderhub_resources/hackmd-template.md
  workshops/build-a-binderhub/binderhub_resources/resource_group1.png
  workshops/build-a-binderhub/binderhub_resources/resource_group2.png
  workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
Labels: ready for merge

#838 Revert "[WIP] Update BinderHub workshop"
  workshops/build-a-binderhub/binderhub_resources/activity_log1.png
  workshops/build-a-binderhub/binderhub_resources/activity_log2.png
  workshops/build-a-binderhub/binderhub_resources/github_oauth.png
  workshops/build-a-binderhub/binderhub_resources/hackmd-template.md
  workshops/build-a-binderhub/binderhub_resources/resource_group1.png
  workshops/build-a-binderhub/binderhub_resources/resource_group2.png
  workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
Labels: approval request

#813 Typo/bug fix in openaccess chapter edit by Esther Plomp
  book/content/open_research/04/openaccess.md
Labels: approval request, bug fixed

#866 [Ready to review/merge] Update credit.md with information on ORCID
  book/content/credit/credit.md
Labels: approval request, book-dash-feb20

#857 [RVW] Migrate CI tests to GitHub Actions
  .github/workflows/lorem-ipsums.yml
  .github/workflows/no-bad-latin.yml
  .github/workflows/prettier.yml
  .github/workflows/test-file-size.yml
  .travis.yml
  scripts/lorem-ipsums.py
  scripts/no-bad-latin.py
  tests/lorem-ipsums.py
  tests/no-bad-latin.py
  tests/test-file-size.sh
Labels: book-dash-feb20, review request, tools

#893 Fix all-contributors config
  .all-contributorsrc
  README.md
Labels: book-dash-feb20

#900 [RVW] Expand definitions of reproducible research
  book/content/reproducibility/03/definitions.md
Labels: book, book-dash-feb20

#908 [RVW] Remove prettier configuration
  .github/workflows/prettier.yml
  .pre-commit-config.yaml
  .prettierignore
Labels: review request

#911 Remove bad latin phrases to fix CI
  book/content/credit/credit.md
  book/content/reproducible_environments/06/containers.md
Labels: approval request, bug fixed

#915 Add demonstrations of including tables into Make chapter
  book/content/make/make.md
Labels: ready for merge

#920 Why reproducibility: minute change in language
  book/content/reproducibility/02/whycare.md
Labels: enhancement, typo-fix
