Repository the-turing-way/the-turing-way, pull requests merged in 2021-11, with the labels that each got.

#2151 Create 2021-11-03-bookdash-github.md
  workshops/github-workshop/2021-11-03-bookdash-github.md
Labels: PR: reviewed-approved

#2154 Added Alden's name
  workshops/github-workshop/2021-11-03-bookdash-github.md
Labels: PR: reviewed-approved

#2141 GitHub chapter review
  book/website/collaboration/github-novice.md
  book/website/collaboration/github-novice/github-novice-advanced.md
  book/website/collaboration/github-novice/github-novice-features.md
  book/website/collaboration/github-novice/github-novice-firststeps.md
  book/website/collaboration/github-novice/github-novice-motivation.md
  book/website/reproducible-research/vcs.md
Labels: PR: reviewed-approved

#2158 Update internal links in github chapter
  book/website/collaboration/github-novice/github-novice-features.md
  book/website/collaboration/github-novice/github-novice-motivation.md
Labels: PR: reviewed-approved

#2156 fix EU2016protection link
  book/website/reproducible-research/open/open-data.md
Labels: PR: unreviewed

#2170 Create .zenodo.json to add metadata on The Turing Way community as author
  .zenodo.json
Labels: PR: partially-approved

#2173 Update .zenodo.json - upload type "Book" -> "Publication"
  .zenodo.json
Labels: PR: reviewed-approved, 0-book-dash-nov21

#2168 Deletes a duplicated sentence in Docker section
  book/website/reproducible-research/renv/renv-containers.md
Labels: PR: reviewed-approved

#2172 reference formatting in open data section
  book/website/reproducible-research/open/open-data.md
Labels: PR: reviewed-approved

#2155 Fix minor typos and wording changes
  book/website/collaboration/maintain-review.md
  book/website/reproducible-research/open/open-access.md
  book/website/reproducible-research/vcs/vcs-github.md
Labels: PR: reviewed-approved

#2159 Tidy up bibliography by removing empty doi field
  book/website/_bibliography/references.bib
Labels: PR: reviewed-approved

#2177 Create CITATION.cff file for The Turing Way
  .zenodo.json
  CITATION.cff
Labels: PR: partially-approved

#2179 Update .zenodo.json because combined license is not recognised
  .zenodo.json
Labels: PR: reviewed-approved

#2163 Fix styling markdown chunks: Closes #2162
  book/templates/chapter-template/chapter-content/chapter-content.md
  book/website/community-handbook/style.md
Labels: PR: partially-approved

#2181 Update .zenodo.json with license cc-by-4.0
  .zenodo.json
Labels: PR: reviewed-approved

#2184 update Citation file to validate with cffconvert
  .zenodo.json
  CITATION.cff
Labels: PR: reviewed-approved

#2186 Er personal values
  book/website/ethical-research/self-reflection.md
  book/website/ethical-research/self-reflection/sr-positionality.md
  book/website/ethical-research/self-reflection/sr-power.md
  book/website/ethical-research/self-reflection/sr-prompts.md
Labels: PR: reviewed-approved

#2195 Fix typo in patricia_herterich.md
  project_management/impact_statements/patricia_herterich.md
Labels: PR: reviewed-approved

#2167 Reviewing and editing Open Access
  book/website/_bibliography/references.bib
  book/website/afterword/glossary.md
  book/website/reproducible-research/open/open-access.md
Labels: PR: reviewed-approved, 0-book-dash-nov21

#2160 Research Infrastructure Roles Chapter + Case Studies
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/collaboration/research-infrastructure-roles.md
  book/website/collaboration/research-infrastructure-roles/community-manager.md
  book/website/collaboration/research-infrastructure-roles/data-steward.md
  book/website/collaboration/research-infrastructure-roles/data-steward/data-steward-casestudy.md
  book/website/collaboration/research-infrastructure-roles/research-software-engineer.md
Labels: help wanted, work-in-progress, collaboration-book, PR: unreviewed, PR: draft, case study, 0-book-dash-nov21

#2169 Ethics Book: Self Reflection Chapter
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/afterword/glossary.md
  book/website/ethical-research/self-reflection.md
  book/website/ethical-research/self-reflection/sr-positionality.md
  book/website/ethical-research/self-reflection/sr-power.md
  book/website/ethical-research/self-reflection/sr-prompts.md
  book/website/ethical-research/self-reflection/sr-resources.md
Labels: PR: unreviewed, 0-book-dash-nov21

#2165 Documentation heading and text added
  book/website/reproducible-research/rdm/rdm-metadata.md
Labels: PR: unreviewed

#2182 [WIP] Adding first draft of recommendations for reusable code
  book/website/_bibliography/references.bib
  book/website/reproducible-research/code-quality.md
  book/website/reproducible-research/code-quality/code-quality-style.md
  book/website/reproducible-research/code-reuse/code-reuse.md
  book/website/reproducible-research/open/open-source.md
Labels: approval request, 0-book-dash-nov21

#2212 Adding new images into the Open Access chapter
  book/website/figures/_figure-list.md
  book/website/figures/routes-to-OA.jpg
  book/website/figures/share-work-openly.jpg
  book/website/reproducible-research/open/open-access.md
Labels: PR: reviewed-approved
