Repository the-turing-way/the-turing-way, pull requests merged in 2021-05, with the labels that each got.

#1785 Describe minimal responsibilities of Turing mybinder Federation administrator
  project_management/turing_mybinder_role.md
Labels: PR: unreviewed

#1868 Files for GitHub workshop to help folks test PRs
  workshops/github-workshop/2021-05-13-intro-workshop.md
Labels: PR: reviewed-approved

#1867 Create 2021-05-13-intro-workshop.md for demo and report
  workshops/github-workshop/2021-05-13-intro-workshop.md
Labels: PR: unreviewed

#1869 Added my details: María Nanton
  workshops/github-workshop/2021-05-13-intro-workshop.md
Labels: PR: reviewed-approved

#1872 Added my details: Lotty Coupat
  workshops/github-workshop/2021-05-13-intro-workshop.md
Labels: PR: reviewed-approved

#1895 Adding Turing Way chapters image.md
  book/website/welcome.md
Labels: PR: reviewed-approved

#1896 Image update rdm-fair.md
  book/website/reproducible-research/rdm/rdm-fair.md
Labels: PR: reviewed-approved

#1672 [WIP] Adding links for glossary terms
  book/website/reproducible-research/open/open-access.md
  book/website/reproducible-research/open/open-data.md
  book/website/reproducible-research/open/open-hardware.md
  book/website/reproducible-research/open/open-notebooks.md
  book/website/reproducible-research/open/open-scholarship.md
  book/website/reproducible-research/open/open-source.md
  book/website/reproducible-research/rdm.md
  book/website/reproducible-research/rdm/rdm-metadata.md
  book/website/reproducible-research/rdm/rdm-sharing.md
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
  book/website/reproducible-research/renv.md
  book/website/reproducible-research/renv/renv-options.md
Labels: work-in-progress

#1898 Added image to reproducible research overview
  book/website/reproducible-research/overview.md
Labels: PR: reviewed-approved

#1900 Adding link to open research image
  book/website/reproducible-research/open.md
Labels: PR: partially-approved

#1902 Add image to Overview
  book/website/reproducible-research/overview/overview-definitions.md
Labels: PR: reviewed-approved

#1903 Add version control image
  book/website/reproducible-research/vcs.md
Labels: PR: reviewed-approved

#1796 Fix "Open Research" link
  book/website/reproducible-research/credit.md
Labels: PR: reviewed-approved

#1791 Make grammar and phrasing changes to Testing Types
  book/website/reproducible-research/testing/testing-types.md
Labels: PR: reviewed-approved

#1790 Make multiple grammar adjustments for the test doubles heading
  book/website/reproducible-research/testing/testing-guidance.md
Labels: PR: reviewed-approved

#1894 Late Test PR
  workshops/github-workshop/2021-05-13-intro-workshop.md
Labels: 0-book-dash-may21, PR: reviewed-approved

#1905 Update a typo in project-design.md
  book/website/project-design/project-design.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed

#1908 Adding ReadableCode image
  book/website/reproducible-research/reviewing/reviewing-workflow.md
Labels: 0-book-dash-may21, PR: unreviewed

#1844 Lightning talk for RightsCon2021: deadline Sunday May 9
  conferences/presentations/RIghtsCon-2021-06-07/script.md
Labels: PR: unreviewed

#1866 French, Italian and Spanish unions added
  book/website/ethical-research/activism/activism-unionisation.md
Labels: PR: reviewed-approved

#1921 Added two images in the credit.md page
  book/website/reproducible-research/credit.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed

#1915 Fix link to University of Leicester Study Skills
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#1857 add short subchapter with interactive learn git resources
  book/website/_toc.yml
  book/website/figures/interactive_learn_git.png
  book/website/reproducible-research/vcs/vcs-git-interactive.md
Labels: PR: reviewed-approved

#1907 Delete duplicated figure
  book/website/figures/RoboDebt.jpg
Labels: 0-book-dash-may21, PR: reviewed-approved, bug fixed

#1918 Expanding Google case study in the activism chapter to a stand-alone subchapter
  book/website/_toc.yml
  book/website/ethical-research/activism-internal-policy.md
  book/website/ethical-research/activism/activism-case-study-google.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed, ethics-book

#1925 Image Update CI.md
  book/website/reproducible-research/ci.md
Labels: PR: unreviewed

#1927 Typo fix
  book/website/collaboration/remote-collab/remote-collab-chairs.md
Labels: PR: reviewed-approved, bug fixed

#1922 Update credit.md to add alt text and break the chapter into smaller subchapter
  book/website/_redirects
  book/website/_toc.yml
  book/website/communication/citable.md
  book/website/communication/citable/citable-checklist.md
  book/website/communication/citable/citable-cite.md
  book/website/communication/citable/citable-orcid.md
  book/website/communication/citable/citable-steps.md
  book/website/community-handbook/contributing/contributing-workflow.md
  book/website/figures/robodebt.jpg
  book/website/reproducible-research/credit.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed

#1793 Remove indentation on image import code
  book/website/reproducible-research/testing/testing-exceptions.md
Labels: PR: reviewed-approved

#1934 Adding an image in the Open Data page
  book/website/_toc.yml
  book/website/reproducible-research/open/open-data.md
Labels: PR: reviewed-approved

#1804 [Ready to review] Add barriers to reproducibility file and associated image
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/afterword/afterword.md
  book/website/communication/citable/citable-orcid.md
  book/website/community-handbook/bookdash.md
  book/website/community-handbook/style/style-figures.md
  book/website/ethical-research/activism/activism-robodebt.md
  book/website/figures/_figure-list.md
  book/website/figures/alt_text_demo.png
  book/website/figures/barriers_reproducibility.png
  book/website/figures/file_collection.jpg
  book/website/figures/first_pull_request.png
  book/website/figures/help_you_of_the_future.jpg
  book/website/figures/make_ok_to_be_human.jpg
  book/website/figures/robo_debt.jpg
  book/website/reproducible-research/overview/overview-barriers.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed, reproducibility-book

#1938 Update copyright year
  book/website/_config.yml
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed, bug fixed

#1946 Fix broken link
  book/website/reproducible-research/rdm/rdm-metadata.md
Labels: PR: reviewed-approved, bug fixed

#1931 Adding BugCatching image
  book/website/reproducible-research/reviewing.md
Labels: 0-book-dash-may21, PR: reviewed-approved

#1932 Adding VersionControl image to Data Storage
  book/website/reproducible-research/rdm/rdm-storage.md
Labels: 0-book-dash-may21, PR: reviewed-approved

#1951 replace duplicate YouTube demo with link to style guide
  book/website/community-handbook/consistency/consistency-formatting.md
Labels: 0-book-dash-may21, PR: reviewed-approved

#1952 improve wording (borrowed wording from the style guide) and add link to the style guide
  CONTRIBUTING.md
Labels: 0-book-dash-may21, PR: reviewed-approved

#1958 fix typo that was causing link to break
  book/website/communication/citable.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed

#1933 Update Image ci-practices .md
  book/website/reproducible-research/ci/ci-practices.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#1954 Fix YouTube capitalization
  book/website/community-handbook/consistency/consistency-formatting.md
  book/website/community-handbook/style/style-custom-styling.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed

#1945 Create rdm-sharing.md
  book/website/reproducible-research/rdm/rdm-sharing.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed
