Repository the-turing-way/the-turing-way, pull requests merged in 2021-01, with the labels that each got.

#1703 Add links to note-taking platforms
  book/website/collaboration/remote-collab/remote-collab-meetings.md
Labels: PR: reviewed-approved

#1700 Update credit.md with ORCID cv
  book/website/reproducible-research/credit.md
Labels: PR: unreviewed

#1708 Update README.md
  conferences/README.md
Labels: PR: partially-approved

#1291 Create a subchapter on data management plans in rdm
  book/website/reproducible-research/rdm/rdm-dmp.md
Labels: PR: unreviewed, reproducibility-book

#1715 Update table of content with the new subchapter on Data Management plan
  book/website/_toc.yml
  book/website/reproducible-research/rdm/rdm-data.md
  book/website/reproducible-research/rdm/rdm-dmp.md
Labels: PR: unreviewed

#1719 Create GSoC 2021 application to submit to INCF
  communications/GSoC-applications/GSoC-2021/GSoC-2021-INCF.md
Labels: PR: reviewed-approved

#1723 Create newsletter_21_Jan2020.md
  communications/newsletters/images/2021-01-Acknowledgement2.jpg
  communications/newsletters/images/2021-01-RemoteBookDash1.jpg
  communications/newsletters/images/2021-01-emma4.png
  communications/newsletters/images/2021-01-ssi3.png
  communications/newsletters/images/2021-01-tweets5.png
  communications/newsletters/newsletter_21_Jan2020.md
Labels: PR: reviewed-approved

#1693 Create newsletter_20_Dec2020.md capturing highlights from December 2020
  communications/newsletters/README.md
  communications/newsletters/images/2020-12-esther-focus-4.png
  communications/newsletters/images/2020-12-hiddenref-tweet-6.png
  communications/newsletters/images/2020-12-ismael-ethics-3.png
  communications/newsletters/images/2020-12-mentored-contri-2.png
  communications/newsletters/images/2020-12-ols-flyer-1.png
  communications/newsletters/images/2020-12-thank-you-7.gif
  communications/newsletters/images/2020-12-ttw-spanish-5.png
  communications/newsletters/newsletter_20_Dec2020.md
Labels: PR: partially-approved

#1722 RightsCon 2021 abstract
  conferences/README.md
  conferences/abstracts/2021-01-RightsCon.md
Labels: PR: unreviewed

#1724 Swap gitter links to Slack links in welcomebot and issue template list
  .github/ISSUE_TEMPLATE/config.yml
  .github/config.yml
Labels: PR: reviewed-approved
