Repository the-turing-way/the-turing-way, pull requests merged in 2021-12, with the labels that each got.

#2216 Adding new contributors image for authorship chapter
  book/website/communication/aa.md
  book/website/figures/acknowledge-authors.jpg
Labels: PR: reviewed-approved

#2217 Adding Collaboration Cafe link
  CONTRIBUTING.md
Labels: PR: unreviewed

#2105 Create September's newsletter and add images
  communications/newsletters/images/2021-10-discussion.png
  communications/newsletters/images/2021-10-emmaweet.png
  communications/newsletters/images/2021-10-giuliaweet.png
  communications/newsletters/images/2021-10-katerinaweet.png
  communications/newsletters/images/2021-10-neilweet.png
  communications/newsletters/images/2021-10-tweets.png
  communications/newsletters/images/2021-10-yanitweet.png
  communications/newsletters/newsletter_29_Sep2021.md
Labels: PR: reviewed-approved

#2059 Create 2021 July's newsletter
  communications/newsletters/README.md
  communications/newsletters/images/2017-07-kw-tweet.png
  communications/newsletters/images/2021-07-comms.png
  communications/newsletters/images/2021-07-faircookbook.png
  communications/newsletters/images/2021-07-mountain.png
  communications/newsletters/images/2021-07-project-design.png
  communications/newsletters/images/2021-07-tools.png
  communications/newsletters/images/2021-07-toptip.png
  communications/newsletters/images/2021-07-tweetcollage.png
  communications/newsletters/newsletter_26_Jun2021.md
  communications/newsletters/newsletter_27_Jul2021.md
  ways_of_working.md
Labels: PR: unreviewed

#2208 Update ci-github-actions.md
  book/website/reproducible-research/ci/ci-github-actions.md
  ways_of_working.md
Labels: typo-fix, PR: unreviewed, PR: reviewed-approved

#2087 fix link formatting issue on open data page
  book/website/afterword/glossary.md
  book/website/communication/aa/aa-equitable.md
  ways_of_working.md
Labels: bug fixed, approval request, PR: unreviewed, PR: reviewed-approved

#2131 fix markdown formatting of nonconsecutive headers
  book/website/reproducible-research/open/open-hardware.md
  book/website/reproducible-research/overview/overview-resources.md
Labels: PR: unreviewed, hacktoberfest-accepted

#2112 Updated open-life-science-mentoring/README
  open-life-science-mentoring/README.md
Labels: PR: unreviewed

#2222 Update Netlify's runtime to Python 3.8
  book/website/runtime.txt
Labels: PR: reviewed-approved

#2219 Update project management docs
  book/website/community-handbook/newsletters.md
  project_management/archive/book_skeleton.md
  project_management/archive/dissemination_plan.md
  project_management/archive/hopes_and_dreams.md
  project_management/archive/jupyter-workshop-application-20191215.md
  project_management/archive/online-collaboration-cafe.md
  project_management/archive/tips_and_tricks_survey.md
  project_management/archive/turing-webpage.md
  project_management/archive/useful-reading.md
  ways_of_working.md
Labels: PR: unreviewed

#2225 Add GitHub handles with links
  ways_of_working.md
Labels: PR: unreviewed

#2221 Added formatR to list of formatter tools
  book/website/reproducible-research/code-quality/code-quality-style.md
Labels: PR: reviewed-approved

#2215 small edits/additions in "Reusable code" section
  book/website/reproducible-research/code-reuse.md
  book/website/reproducible-research/code-reuse/code-reuse-details.md
  book/website/reproducible-research/code-reuse/code-reuse-overview.md
Labels: PR: unreviewed

#2201 Metadata sharing and management
  book/website/reproducible-research/rdm/rdm-metadata.md
Labels: PR: reviewed-approved, 0-book-dash-nov21

#2234 Github -> GitHub
  book/website/_toc.yml
  book/website/collaboration/github-novice.md
Labels: PR: reviewed-approved
