Repository the-turing-way/the-turing-way, pull requests merged in 2021-02, with the labels that each got.

#1728 BF: Fix stale links to TU Delft's RDM portal
  book/website/reproducible-research/rdm/rdm-dmp.md
Labels: PR: reviewed-approved

#1742 Remove duplication of "Disambiguation" list
  book/website/reproducible-research/renv/renv-binder.md
Labels: PR: reviewed-approved

#1692 Book Dash Nov 2020 Report and update templates for remote book dash as per Nov 2020 event
  workshops/book-dash/book-dash-nov20-report.md
  workshops/book-dash/figures/Nov20-BookDash.png
  workshops/book-dash/organisers_files-2020/book-dash-shared-hackmd/bookdash-feb20.md
  workshops/book-dash/organisers_files-2020/book-dash-shared-hackmd/bookdash-nov20.md
  workshops/book-dash/organisers_files-2020/hackmd-template-in-person.md
  workshops/book-dash/organisers_files-2020/hackmd-template-remote.md
  workshops/book-dash/organisers_files-2020/planning-checklist-issue.md
  workshops/book-dash/organisers_files-2020/pluses-and-deltas/pluses-and-deltas-feb20.md
  workshops/book-dash/organisers_files-2020/pluses-and-deltas/pluses-and-deltas-nov20.md
  workshops/book-dash/organisers_files-2020/pre-dash-call-template.md
  workshops/book-dash/organisers_files-2020/pre-dash-notes/pre-dash-call-notes-feb20.md
  workshops/book-dash/organisers_files-2020/pre-dash-notes/pre-dash-notes-nov20.md
  workshops/book-dash/organisers_files-2020/shared-plan/shared-plan-feb20.md
  workshops/book-dash/organisers_files-2020/shared-plan/shared-plan-nov20.md
Labels: PR: partially-approved

#1741 Remove unnecessary apostrophe
  book/website/reproducible-research/rdm/rdm-checklist.md
Labels: PR: reviewed-approved

#1739 Add determiner to "online Git repository"
  book/website/reproducible-research/vcs/vcs-github.md
Labels: PR: reviewed-approved

#1730 Update rdm-fair.md
  book/website/_bibliography/references.bib
  book/website/reproducible-research/rdm/rdm-fair.md
  book/website/reproducible-research/rdm/rdm-metadata.md
Labels: PR: reviewed-approved, reproducibility-book, review request

#1738 Add CW21 abstract and invite volunteers to co-lead this
  conferences/README.md
  conferences/abstracts/2021-03-CW21.md
Labels: PR: unreviewed

#1747 Create newsletter_21_Feb2021.md draft
  communications/newsletters/images/2021-02-batool-tweet-4.png
  communications/newsletters/images/2021-02-laura-carter-3.png
  communications/newsletters/images/2021-02-sarah-tweet-2.png
  communications/newsletters/images/2021-02-scigen-repro-def-5.png
  communications/newsletters/images/2021-02-stairway-consistency-1.png
  communications/newsletters/images/2021-02-tweet-collage-6.png
  communications/newsletters/newsletter_21_Feb2021.md
Labels: PR: unreviewed

#1744 Change master branch references to main or HEAD
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-julia.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-r.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-solo.md
Labels: PR: reviewed-approved

#1757 Update links and Gitter section in contributing guide
  CONTRIBUTING.md
Labels: PR: unreviewed

#1761 Maintaining Consistency in github-resources.md
  book/website/_toc.yml
  book/website/collaboration/github/github-resources.md
Labels: PR: reviewed-approved

#1762 Maintaining Consistency in github-maintainers.md; restructuring subchapter as chapter
  book/website/_toc.yml
  book/website/collaboration/github/github-maintainers.md
  book/website/collaboration/maintain-review.md
  book/website/collaboration/maintain-review/maintain-review-maintenance.md
  book/website/collaboration/maintain-review/maintain-review-merge.md
  book/website/collaboration/maintain-review/maintain-review-permissions.md
  book/website/collaboration/maintain-review/maintain-review-resources.md
  book/website/collaboration/maintain-review/maintain-review-review.md
Labels: PR: reviewed-approved
