Repository the-turing-way/the-turing-way, pull requests merged in 2021-08, with the labels that each got.

#2010 Remove advice to use C++ testing frameworks for C
  book/website/reproducible-research/testing/testing-guidance.md
Labels: PR: reviewed-approved

#2058 Errant underscore
  book/website/collaboration/new-community.md
Labels: PR: reviewed-approved, typo-fix

#2062 Updating the Book dash chapter in community handbook
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/afterword/contributors-record.md
  book/website/community-handbook/bookdash.md
  book/website/community-handbook/bookdash/bookdash-after.md
  book/website/community-handbook/bookdash/bookdash-events.md
  book/website/community-handbook/bookdash/bookdash-logistics.md
  book/website/community-handbook/bookdash/bookdash-preparation.md
  book/website/community-handbook/bookdash/bookdash-selection.md
  book/website/community-handbook/templates.md
  book/website/community-handbook/templates/template-bookdash-github.md
  book/website/community-handbook/templates/template-bookdash-index.md
  book/website/community-handbook/templates/template-bookdash-issue.md
  book/website/community-handbook/templates/template-bookdash-notes.md
  book/website/community-handbook/templates/template-bookdash-precall.md
Labels: work-in-progress, PR: unreviewed

#2075 Correcting names for links to subchapters
  book/website/project-design/project-repo.md
Labels: PR: unreviewed
