Repository the-turing-way/the-turing-way, pull requests merged in 2021-04, with the labels that each got.

#1805 Updating Activism chapter with minor edits + relocating Internal Policy Advocacy sub-chapter
  book/website/_toc.yml
  book/website/ethical-research/activism-internal-policy.md
  book/website/ethical-research/activism.md
  book/website/ethical-research/activism/activism-unionisation.md
Labels: PR: reviewed-approved

#1841 Fix a typo
  book/website/ethical-research/activism/activism-unionisation.md
Labels: PR: reviewed-approved

#1835 Create GSoC-2021.md file for initial application
  communications/GSOD-applications/GSoC-2021.md
Labels: PR: reviewed-approved

#1740 Indent numbered list blocks to avoid number reset
  book/website/reproducible-research/vcs/vcs-github.md
Labels: PR: reviewed-approved

#1839 Create newsletter_23_Mar2021.md late release for this month
  communications/newsletters/images/2021-03-BA-4.png
  communications/newsletters/images/2021-03-KW-1.png
  communications/newsletters/images/2021-03-LA-2.png
  communications/newsletters/images/2021-03-binder-5.png
  communications/newsletters/images/2021-03-robodebt-3.png
  communications/newsletters/images/2021-03-tweets-6.png
  communications/newsletters/newsletter_21_Jan2021.md
  communications/newsletters/newsletter_22_Feb2021.md
  communications/newsletters/newsletter_23_Mar2021.md
Labels: PR: reviewed-approved

#1830 fix: Maintaining Consistency in collaboration.md
  book/website/collaboration/collaboration.md
  book/website/collaboration/github-collaboration.md
  book/website/collaboration/github/github-roadmapping.md
Labels: PR: reviewed-approved

#1746 Add the DOI of the talk to the table
  conferences/README.md
Labels: PR: unreviewed

#1004 [WIP] improve research compendia chapter
  book/website/reproducible-research/compendia.md
Labels: typo-fix, work-in-progress

#1764 Update Data sharing and archiving in the RDM book with a Data Availability Statement section and fix duplication with Open Data section
  book/website/reproducible-research/open/open-data.md
  book/website/reproducible-research/rdm/rdm-sharing.md
Labels: PR: unreviewed, review request

#1781 Two grammar changes
  book/website/reproducible-research/code-quality.md
Labels: PR: reviewed-approved

#1788 Add commas for clarity on lines 57 and 59
  book/website/reproducible-research/testing.md
Labels: PR: reviewed-approved

#1795 Add hyperlink alias
  book/website/reproducible-research/compendia.md
Labels: PR: reviewed-approved

#1794 Fix typo
  book/website/reproducible-research/reviewing/reviewing-recommend.md
Labels: PR: reviewed-approved

#1824 Update grammar in risk-assess.md
  book/website/reproducible-research/risk-assess.md
Labels: PR: reviewed-approved

#1848 [Review Needed]Add labels and improve grammar in os-comms-issue-tracking.md.
  book/website/communication/os-comms/os-comms-issue-tracking.md
Labels: PR: reviewed-approved

#1779 Add "tips" section
  book/website/community-handbook/style.md
Labels: PR: reviewed-approved

#1822 Improve grammar in compendia.md
  book/website/reproducible-research/compendia.md
Labels: PR: unreviewed

#1823 Update hyperlink so it renders in Netlify build
  book/website/reproducible-research/compendia.md
Labels: PR: unreviewed

#1853 Update contributors.md
  contributors.md
Labels: PR: unreviewed
