Repository the-turing-way/the-turing-way, pull requests merged in 2021-07, with the labels that each got.

#1963 Add June 2021 newsletter and update Apr-May newsletter branch
  communications/newsletters/images/2021-04-bbs-anabasiri-2.png
  communications/newsletters/images/2021-04-hiddenref-3.png
  communications/newsletters/images/2021-04-opensourcecollab-1.png
  communications/newsletters/images/2021-04-ssifellows2021-4.png
  communications/newsletters/images/2021-04-tweetcollage-5.png
  communications/newsletters/images/2021-05-advocacy-5.png
  communications/newsletters/images/2021-05-aidatweet-2.png
  communications/newsletters/images/2021-05-bookdashattendees-3.png
  communications/newsletters/images/2021-05-communicating-7.png
  communications/newsletters/images/2021-05-culturepanel-8.png
  communications/newsletters/images/2021-05-ninatweet-6.png
  communications/newsletters/images/2021-05-planningcommittee-4.png
  communications/newsletters/images/2021-05-roadmap-1.png
  communications/newsletters/images/2021-05-sarahtweet-9.png
  communications/newsletters/newsletter_24_Apr2021.md
  communications/newsletters/newsletter_25_May2021.md
Labels: PR: unreviewed

#1988 Create June 2021 newsletter
  communications/newsletters/images/2021-06-humanrights.png
  communications/newsletters/images/2021-06-mariatweet.png
  communications/newsletters/images/2021-06-marta.png
  communications/newsletters/images/2021-06-meeting.png
  communications/newsletters/images/2021-06-ols.png
  communications/newsletters/images/2021-06-openscience.png
  communications/newsletters/images/2021-06-projectdesign.png
  communications/newsletters/images/2021-06-tweetcollage.png
  communications/newsletters/newsletter_26_June2021.md
Labels: PR: unreviewed

#1936 Add the draft for project design overview
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/communication/citable.md
  book/website/communication/citable/citable-cite.md
  book/website/communication/citable/citable-orcid.md
  book/website/communication/citable/citable-resources.md
  book/website/communication/citable/citable-steps.md
  book/website/project-design/pd-overview.md
  book/website/project-design/pd-overview/pd-overview-methods.md
  book/website/project-design/pd-overview/pd-overview-planning.md
  book/website/project-design/pd-overview/pd-overview-repro.md
  book/website/project-design/pd-overview/pd-overview-sharing.md
  book/website/project-design/pd-overview/pd-overview-version.md
  book/website/project-design/project-repo/project-repo-advanced.md
  book/website/project-design/project-repo/project-repo-resources.md
Labels: 0-book-dash-may21, PR: unreviewed

#1993 Created File for PR Activity
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: partially-approved

#2007 Update 2021-07-05-intro-workshop.md
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#2005 Added my name and information
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#2004 Adding information to name
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#2001 ADD comment by my name
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#1999 Add my name to 2021-07-05-intro-workshop.md
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: partially-approved

#1997 EDIT added info against my name
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#2009 ADD info next to name Victoria
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#2008 EDIT added info on my line
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#2003 EDIT added info to my own name
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: reviewed-approved

#1996 Edit my name in roster
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: unreviewed

#1998 Added info after name
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: unreviewed

#2000 Edit my name in roster
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: unreviewed

#2002 Updated against my name
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: unreviewed

#1994 Updated for Ben
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: unreviewed

#2006 Update 2021-07-05-intro-workshop.md
  workshops/github-workshop/2021-07-05-intro-workshop.md
Labels: PR: unreviewed

#2016 Tweak CI triggers to exclude all-contributors bot
  .github/workflows/ci.yml
  .github/workflows/lorem-ipsums.yml
  .github/workflows/no-bad-latin.yml
  netlify.toml
Labels: PR: partially-approved

#2024 Fix broken links to chapter template
  book/website/community-handbook/consistency.md
  book/website/community-handbook/consistency/consistency-structure.md
Labels: PR: reviewed-approved

#1992 Minor error fixing in the Project Design Overview chapter
  book/website/project-design/pd-overview/pd-overview-repro.md
  book/website/project-design/project-design.md
Labels: PR: unreviewed

#2025 Create citable-linking.md
  book/website/_toc.yml
  book/website/communication/citable/citable-cite.md
  book/website/communication/citable/citable-linking.md
  book/website/reproducible-research/rdm/rdm-sharing.md
Labels: PR: unreviewed

#2026 fixing image link for DOI image
  book/website/communication/citable/citable-steps.md
Labels: PR: reviewed-approved

#1949 Update make examples
  book/website/reproducible-research/make/make-examples.md
Labels: 0-book-dash-may21, PR: reviewed-approved, PR: unreviewed

#1961 Updating the landing page
  book/website/welcome.md
Labels: PR: reviewed-approved

#2029 updates guide name and fixes some links
  book/website/ethical-research/activism.md
Labels: PR: reviewed-approved

#1491 Minor cleanup for the github workflow page
  book/website/reproducible-research/vcs/vcs-github.md
Labels: PR: unreviewed, book-dash-nov20, hacktoberfest-accepted

#2039 Update jupyter book version to 0.11.2
  book/website/_toc.yml
  book/website/requirements.txt
Labels: PR: reviewed-approved

#2041 Creating OSF21- collaboration workshop abstract
  conferences/abstracts/2021-09-OSF21-collboration-workshop.md
Labels: PR: unreviewed

#2032 Harmonise README and Landing file
  README.md
  book/website/figures/README_imgs/.gitkeep
  book/website/figures/README_imgs/README_book.png
  book/website/figures/README_imgs/README_contributions.png
  book/website/figures/README_imgs/README_turingway.png
  book/website/reproducible-research/ci.md
  book/website/welcome.md
Labels: PR: unreviewed

#2042 Remove web analytics code until we get an approval from the Turing Legal team
  book/website/analytics/web-analytics.js
Labels: PR: reviewed-approved

#2038 Update contributors files and contributors workflow
  book/website/afterword/contributors-record.md
  book/website/scripts/contributors.sh
  collaborating_projects.md
  tests/contributors.sh
Labels: PR: unreviewed

#2052 fix broken links in readme
  README.md
Labels: PR: reviewed-approved, review request

#1858 Create a new chapter on shared ownership
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/collaboration/shared-ownership.md
  book/website/collaboration/shared-ownership/shared-ownership-challenges.md
  book/website/collaboration/shared-ownership/shared-ownership-defaults.md
  book/website/collaboration/shared-ownership/shared-ownership-models.md
  book/website/collaboration/shared-ownership/shared-ownership-projects.md
  book/website/figures/github-roles.png
  book/website/figures/mountain-of-engagement.png
Labels: PR: unreviewed

#2019 Tag curated chapters for the data study group
  book/website/collaboration/github-novice.md
  book/website/collaboration/remote-collab/remote-collab-coworking.md
  book/website/collaboration/remote-collab/remote-collab-guidelines.md
  book/website/collaboration/remote-collab/remote-collab-meetings.md
  book/website/collaboration/remote-collab/remote-collab-participation.md
  book/website/collaboration/remote-collab/remote-collab-tools.md
  book/website/ethical-research/ethics-case-study.md
  book/website/ethical-research/ethics-intro.md
  book/website/project-design/pd-overview/pd-overview-planning.md
  book/website/reproducible-research/licensing/licensing-data.md
  book/website/reproducible-research/open.md
  book/website/reproducible-research/open/open-data.md
  book/website/reproducible-research/overview.md
Labels: PR: partially-approved

#2057 Update HackMD link in the collaboration cafe
  book/website/community-handbook/coworking/coworking-collabcafe.md
Labels: PR: reviewed-approved
