Repository the-turing-way/the-turing-way, pull requests merged in 2021-09, with the labels that each got.

#1471 [WIP] Create chapter on Managing personal data
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/reproducible-research/rdm/rdm-personal.md
Labels: hacktoberfest-accepted

#2091 Updating Sarah's contributor record
  contributors.md
Labels: PR: unreviewed

#2099 Create 2021-12-07-FORCE2021-lightening.md
  conferences/abstracts/2021-12-07-FORCE2021-lightening.md
Labels: PR: unreviewed

#2063 Academic authorship chapter for Guide for Communication
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/afterword/glossary.md
  book/website/communication/aa.md
  book/website/communication/aa/equitable.md
  book/website/communication/aa/interdisciplinary-personal-stories.md
  book/website/communication/aa/large-personal-stories.md
  book/website/communication/aa/misconduct.md
  book/website/communication/aa/overview.md
  book/website/communication/aa/resources.md
  book/website/communication/aa/tips.md
  book/website/communication/aa/traditions.md
  book/website/community-handbook/acknowledgement/acknowledgement-members.md
Labels: communication-book, PR: unreviewed, PR: reviewed-approved

#2095 Fix incorrect link on readme
  README.md
Labels: bug fixed, approval request, PR: unreviewed, PR: reviewed-approved

#2093 fix makefile
  book/website/reproducible-research/make/make-examples.md
Labels: PR: reviewed-approved

#2096 make link more precise to make it easier to check whether there are open pull requests from the allcontributors bot
  CONTRIBUTING.md
Labels: approval request, PR: unreviewed, PR: reviewed-approved

#2092 Update README info for citing illustrations
  README.md
Labels: typo-fix, PR: unreviewed, PR: reviewed-approved, 0-book-dash-may21
