Repository the-turing-way/the-turing-way, pull requests merged in 2021-03, with the labels that each got.

#1767 Fix link to postBuild section
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
Labels: PR: reviewed-approved

#1770 Add files via upload
  book/website/figures/ScientificUnionBadge.jpg
Labels: PR: reviewed-approved

#1675 [WIP]: write Activism chapter
  book/website/_toc.yml
  book/website/community-handbook/style/style-figures.md
  book/website/ethical-research/activism.md
  book/website/ethical-research/activism/activism-internal-policy.md
  book/website/ethical-research/activism/activism-robodebt.md
  book/website/ethical-research/activism/activism-unionisation.md
  book/website/ethical-research/activism/activism-whistleblowing.md
  book/website/figures/alt-text-demo.png
  book/website/figures/scientificunionbadge.png
Labels: ethics-book, help wanted

#1771 Update _figure-list.md - add scientific union badge to the list
  book/website/figures/_figure-list.md
Labels: PR: reviewed-approved

#1763 Merge January newsletter to master
  communications/newsletters/images/2021-01-Acknowledgement2.jpg
  communications/newsletters/images/2021-01-RemoteBookDash1.jpg
  communications/newsletters/images/2021-01-emma4.png
  communications/newsletters/images/2021-01-ssi3.png
  communications/newsletters/images/2021-01-tweets5.png
  communications/newsletters/newsletter_21_Jan2020.md
Labels: PR: reviewed-approved

#1759 Fix link in table of contents
  CODE_OF_CONDUCT.md
Labels: PR: reviewed-approved

#1745 Fixing jupyter warning
  book/website/collaboration/new-community/new-community-guide.md
  book/website/collaboration/remote-collab/remote-collab-conferences.md
  book/website/collaboration/remote-collab/remote-collab-participation.md
  book/website/community-handbook/consistency/consistency-language.md
  book/website/community-handbook/coworking/coworking-organisation.md
  book/website/community-handbook/newsletters/newsletters-process.md
Labels: PR: reviewed-approved

#1769 [Review needed] Create 03-2021-CW21LT.md
  conferences/abstracts/2021-03-CW21LT.md
Labels: PR: unreviewed

#1782 Make several grammar improvements
  book/website/reproducible-research/code-quality/code-quality-style.md
Labels: PR: reviewed-approved

#1775 Update typo: "chater" to "chapter"
  book/website/reproducible-research/renv/renv-vm.md
Labels: PR: reviewed-approved

#1780 Fix hyperlink that did not parse
  book/website/reproducible-research/renv/renv-containers.md
Labels: PR: reviewed-approved

#1768 Fix link in Zero to Binder Python docs
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
Labels: PR: reviewed-approved

#1783 Fix example label directive to have ")=" at the end
  book/website/community-handbook/style/style-crossref.md
Labels: PR: reviewed-approved

#1776 Compress two blockquotes into one
  book/website/reproducible-research/renv/renv-containers.md
Labels: PR: reviewed-approved

#1784 Remove R example from paired examples for workshop
  workshops/boost-research-reproducibility-binder/paired_examples.md
Labels: PR: reviewed-approved

#1552 [Ready for Review] Update BinderHub workshop
  workshops/build-a-binderhub/binderhub_resources/activity_log1.png
  workshops/build-a-binderhub/binderhub_resources/activity_log2.png
  workshops/build-a-binderhub/binderhub_resources/collaborative_notes_template.md
  workshops/build-a-binderhub/binderhub_resources/github_oauth.png
  workshops/build-a-binderhub/binderhub_resources/resource_group1.png
  workshops/build-a-binderhub/binderhub_resources/resource_group2.png
  workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
Labels: PR: reviewed-approved, book-dash-nov20

#1801 Update headings to maintain consistency
  book/website/collaboration/github/github-contributors.md
Labels: PR: reviewed-approved

#705 Add barrier 2 (publication bias) to barriers.md in reproducibility chapter
  book/content/reproducibility/04/barriers.md
Labels: reproducibility-book

#706 Add barrier 3 (higher standards) to barriers.md in reproducibility chapter
  book/content/reproducibility/04/barriers.md
Labels: PR: unreviewed, reproducibility-book

#707 Add barrier 9 (reproducible not right) to barriers.md in reproducibility chapter
  book/content/reproducibility/04/barriers.md
Labels: PR: unreviewed, reproducibility-book

#703 Add barrier 8 (big data) to barriers.md in reproducibility chapter
  book/content/reproducibility/04/barriers.md
Labels: reproducibility-book

#701 Add barrier 4 (considered for promotion) to barriers.md in reproducibility chapter
  book/content/reproducibility/04/barriers.md
Labels: PR: unreviewed, reproducibility-book

#1748 Preview/test Matomo analytics on this branch
  book/website/_static/web-analytics.js
Labels: PR: unreviewed

#1820 fix: Maintaining Consistency in github-readme
  book/website/collaboration/github/github-readme.md
Labels: PR: reviewed-approved

#1826 Add robodebt image
  book/website/ethical-research/activism/activism-robodebt.md
  book/website/figures/_figure-list.md
  book/website/figures/robodebt.jpg
Labels: PR: reviewed-approved

#1827 Update link to Matrix chat room
  README.md
Labels: PR: reviewed-approved

#1832 Update link to reflect renaming of Riot to Element
  book/website/collaboration/new-community/new-community-guide.md
Labels: PR: reviewed-approved

#1821 Adding primary language for screen reader accessibility
  book/website/_config.yml
Labels: PR: reviewed-approved

#1807 Add Determine Assumed Knowledge Between Diverse Team Members
  book/website/collaboration/new-community/new-community-differences.md
Labels: PR: reviewed-approved

#1808 Update new-community-techissues.md
  book/website/collaboration/new-community/new-community-differences.md
  book/website/collaboration/new-community/new-community-techissues.md
Labels: PR: unreviewed
