Repository the-turing-way/the-turing-way, pull requests merged in 2022-01, with the labels that each got.

#2244 Update rdm.md
  book/website/figures/data-ecosystem.jpg
  book/website/reproducible-research/rdm.md
Labels: PR: reviewed-approved

#2242 Fix mark-up
  book/website/reproducible-research/overview/overview-resources.md
Labels: PR: reviewed-approved

#2243 [Ready for review]: Fix duplicate paragraph
  book/website/reproducible-research/code-quality/code-quality-style.md
  book/website/reproducible-research/reviewing/reviewing-motivation.md
  book/website/reproducible-research/reviewing/reviewing-recommend.md
Labels: PR: unreviewed

#2238 Update Ismael-KG's contributor record
  book/website/afterword/contributors-record.md
  contributors.md
Labels: PR: reviewed-approved

#2241 Add checklist for chairing coworking sessions
  book/website/community-handbook/coworking/coworking-collabcafe.md
  book/website/community-handbook/coworking/coworking-weekly.md
Labels: PR: unreviewed

#2239 Add teamwork section to 'Managing a New Community and Team' chapter
  book/website/_toc.yml
  book/website/collaboration/new-community.md
  book/website/collaboration/new-community/new-community-teamwork.md
  book/website/project-design/pd-overview/pd-overview-repro.md
Labels: PR: unreviewed

#2231 Add UX/UI proposal to the project management folder
  project_management/2021-07-ux-funding-turing.md
Labels: PR: partially-approved

#2237 Update Solidarity Bot configuration
  .github/in-solidarity.yml
Labels: PR: partially-approved
