Repository the-turing-way/the-turing-way, pull requests merged in 2022-08, with the labels that each got.

#2482 Create CrapentriesCon collab-party-doc
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2117 Updated README-French.md
  README-translated/README-French.md
Labels: translation, review request, PR: unreviewed, PR: reviewed-approved, good first PR review, Hacktoberfest

#2495 CarpentryCon: Add numbers to workshop file
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2510 Updated CarpentriesCon GitHub Workshop
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2517 Updated CarpentriesCon GitHub Workshop
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2484 Fix tiny mini typo in main README.md
  README.md
Labels: PR: reviewed-approved

#2511 Updated README.md
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2514 Updated CarpentriesCon GitHub Workshop File
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: partially-approved

#2516 Updated the Carpentries Con MD document
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2497 CarpentryCon: Sample Pull Request
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: good first issue, PR: unreviewed, PR: partially-approved, carpentrycon22

#2518 Update 2022-08-04-carpentriescon.md
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2524 remove unnecessary comments
  book/website/ethical-research/preclinical-research.md
Labels: PR: reviewed-approved

#2522 Update citable-cite.md: Citing Research Objects' #2485
  book/website/communication/citable/citable-cite.md
Labels: PR: reviewed-approved

#2521 Fix broken link
  book/website/reproducible-research/rdm/rdm-personal.md
Labels: PR: partially-approved

#2529 Updated number of contributors
  book/website/reproducible-research/reproducible-research.md
Labels: PR: reviewed-approved, carpentrycon22

#2512 Updated CarpentriesCon GitHub Workshop README
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved, carpentrycon22

#2519 Change gitter link to the slack workspace
  book/website/community-handbook/bookdash/bookdash-after.md
Labels: PR: reviewed-approved, carpentrycon22

#2520 Updated rdm-fair.md
  book/website/reproducible-research/rdm/rdm-fair.md
Labels: PR: partially-approved, carpentrycon22

#2525 Updated resources
  book/website/reproducible-research/rdm/rdm-personal.md
Labels: PR: partially-approved, carpentrycon22

#2527 fix-spacing-issue
  book/website/collaboration/github-novice/github-novice-motivation.md
Labels: PR: reviewed-approved, carpentrycon22

#2528 Style/grammar correction in rdm-fair.md
  book/website/reproducible-research/rdm/rdm-fair.md
Labels: PR: partially-approved, carpentrycon22

#2061 [Ready for Review] Updating README (ITA)
  README-translated/README-Italian.md
Labels: translation, PR: unreviewed, PR: reviewed-approved, hacktoberfest-accepted

#2537 Updated communication.md file for #2509
  book/website/communication/communication.md
Labels: good first issue, PR: unreviewed, PR: reviewed-approved, carpentrycon22

#2543 Remove line "Conversation as Collaboration"
  book/website/communication/os-comms.md
Labels: PR: reviewed-approved

#2558 Updated gitter link to slack workspace link
  book/website/project-design/persona/persona-contributors.md
Labels: PR: reviewed-approved

#2560 Added a resource
  book/website/reproducible-research/rdm/rdm-storage.md
Labels: PR: reviewed-approved

#2474 Add Slack on prominent/visible places
  README.md
  book/website/welcome.md
Labels: PR: partially-approved, good first PR review

#2561 Added resource, video on elements of a DMP
  book/website/reproducible-research/rdm/rdm-dmp.md
Labels: PR: reviewed-approved

#2559 clearify wording in introduction
  book/website/communication/communication.md
Labels: PR: partially-approved

#2578 typo fixed #2556
  book/website/ethical-research/ethics-committees.md
Labels: PR: reviewed-approved

#2568 fixed typo and changed link
  book/website/ethical-research/ethics-committees.md
Labels: PR: unreviewed

#2587 Fixes hyperlinking Malvika Sharan
  book/website/community-handbook/community-handbook.md
Labels: PR: reviewed-approved

#2594 Update give_a_talk.yml
  .github/ISSUE_TEMPLATE/give_a_talk.yml
Labels: PR: reviewed-approved

#2571 Automate closing talk issues in a workflow
  .github/workflows/close-talk-issues.yml
Labels: project management, PR: unreviewed, PR: draft

#2307 Update Jupyter Book version
  book/website/communication/binder/zero-to-binder.md
  book/website/requirements.txt
Labels: help wanted, review request, PR: unreviewed, PR: reviewed-approved

#2603 Add a warning about the automated workflow to the end of the talk checklist issue
  .github/ISSUE_TEMPLATE/give_a_talk.yml
Labels: PR: reviewed-approved

#2600 Bugfixing the close-talks-issues.yaml workflow
  .github/workflows/close-talk-issues.yml
Labels: PR: partially-approved

#2607 added link to slack to 'ttw slack' issue template
  .github/ISSUE_TEMPLATE/give_a_talk.yml
Labels: PR: reviewed-approved

#2596 Add links to Packaging Systems section
  book/website/reproducible-research/renv/renv-package.md
Labels: PR: reviewed-approved

#2593 Fix markdown syntax error for email
  book/website/community-handbook/coc.md
Labels: PR: reviewed-approved

#2622 Bumping the version of python used in CI to 3.10
  .github/workflows/ci.yml
Labels: PR: partially-approved, infrastructure

#2619 Modify duplicate labels
  book/website/communication/open.md
  book/website/ethical-research/ethics-open-source-governance.md
  book/website/reproducible-research/open.md
Labels: book-build, typo-fix, PR: unreviewed, PR: partially-approved, caretaking

#2620 typo which breaks reference
  book/website/project-design/sdp/pd-sdp-private-learning.md
Labels: book-build, typo-fix, PR: unreviewed, PR: partially-approved
