Repository the-turing-way/the-turing-way, pull requests merged in 2022-06, with the labels that each got.

#2413 Refactor release_workflow.py to use a YAML parser
  .github/workflows/release-drafter.yml
  .github/workflows/release-workflow.yml
  tests/release_workflow.py
  tests/requirements.txt
Labels: PR: unreviewed

#2338 Reference the Open Definition in open.md
  book/website/reproducible-research/open.md
Labels: PR: reviewed-approved

#2400 Added name to project members
  ways_of_working.md
Labels: PR: reviewed-approved, good first PR review

#1735 Add 2020-2022 Turing-TPS report to the communication folder
  project_management/legacy-documents/dissemination_plan.md
  project_management/legacy-documents/hopes_and_dreams.md
  project_management/legacy-documents/online-collaboration-cafe.md
  project_management/legacy-documents/resources.md
  project_management/legacy-documents/turing-webpage.md
  project_management/legacy-documents/useful-reading.md
  project_management/proposals/jupyter-workshop-application-20191215.md
  project_management/proposals/tps-funding-application-20190429.md
  project_management/quarterly_reports/2020-turing-tps-report.md
  project_management/quarterly_reports/2021-turing-tps-report.md
  project_management/quarterly_reports/2022-turing-tps-report.md
Labels: PR: unreviewed

#2424 Remove given-names field in CITATION.cff file
  CITATION.cff
Labels: PR: unreviewed

#2414 Fixing typos/grammar
  book/website/project-design/pd-overview/pd-overview-repro.md
Labels: approval request, PR: unreviewed, PR: reviewed-approved, good first PR review

#2418 Fix typo
  book/website/reproducible-research/licensing/licensing-data.md
Labels: typo-fix, approval request, PR: reviewed-approved, good first PR review

#2415 Spelling/grammar fixes
  book/website/project-design/pd-overview/pd-overview-version.md
Labels: approval request, PR: unreviewed, PR: reviewed-approved, good first PR review

#2433 Fix typo in micro.md
  book/website/communication/dif-articles/micro.md
Labels: PR: reviewed-approved

#2423 Testing section: indentation fixes
  book/website/reproducible-research/testing/testing-runtime.md
  book/website/reproducible-research/testing/testing-unittest.md
Labels: PR: reviewed-approved
