Repository the-turing-way/the-turing-way, pull requests merged in 2022-05, with the labels that each got.

#2295 Binder credit reqs
  project_management/credit_requests/turing_mybinder_azure_credit_request_2021-12.md
  project_management/credit_requests/turing_mybinder_azure_credit_request_2022-03.md
Labels: PR: unreviewed

#2340 Update Binder credit request template
  project_management/credit_requests/turing_mybinder_azure_credit_request_template.md
Labels: PR: partially-approved

#2342 Updated ways_of_working.md
  ways_of_working.md
Labels: PR: reviewed-approved

#2341 Update open-access.md with Vicky's video on open access
  book/website/reproducible-research/open/open-access.md
Labels: PR: reviewed-approved

#2355 (get external fork in the book repo) data versioning
  book/website/_toc.yml
  book/website/reproducible-research/vcs/vcs-git-general.md
  book/website/reproducible-research/vcs/vcs-git-in-research.md
  book/website/reproducible-research/vcs/vcs-workflow.md
Labels: PR: unreviewed

#2336 [WIP] Editing newsletter chapter
  book/website/community-handbook/newsletters/newsletters-process.md
  book/website/community-handbook/newsletters/newsletters-style.md
Labels: help wanted, PR: draft, community-handbook

#2369 Update rdm-sharing to fix hyperlink
  book/website/reproducible-research/rdm/rdm-sharing.md
Labels: PR: reviewed-approved, 0-book-dash-may22

#2363 Update rdm-sharing.md with illustration
  book/website/reproducible-research/rdm/rdm-sharing.md
Labels: PR: reviewed-approved

#2385 Update os-comms.md
  book/website/communication/os-comms.md
Labels: PR: reviewed-approved

#2339 Create pd-sdp-private-learning.md
  book/website/_bibliography/references.bib
  book/website/project-design/sdp.md
  book/website/project-design/sdp/pd-sdp-private-learning.md
Labels: PR: unreviewed, 0-book-dash-may22

#2384 Add chapter on Open Scholarship and section on Open Education to Communication guide
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/communication/comms-overview.md
  book/website/communication/communication.md
  book/website/communication/open.md
  book/website/communication/open/education.md
  book/website/reproducible-research/open/open-scholarship.md
Labels: PR: unreviewed, 0-book-dash-may22

#2353 [ready for review] New open research articles chapter
  book/website/_toc.yml
  book/website/communication/dif-articles.md
  book/website/communication/dif-articles/data.md
  book/website/communication/dif-articles/methods.md
  book/website/communication/dif-articles/micro.md
  book/website/communication/dif-articles/reg.md
  book/website/communication/dif-articles/software.md
  book/website/communication/new-articles.md
  book/website/figures/cos-reg-reports.png
  book/website/figures/publishing-diff-articles.jpg
Labels: communication-book, PR: unreviewed, PR: reviewed-approved, 0-book-dash-may22

#2383 Chinese Translation of current latest README.md
  README-translated/README-Chinese.md
Labels: PR: partially-approved, 0-book-dash-may22

#2382 Singularity GPU support
  book/website/reproducible-research/renv/renv-containers.md
Labels: PR: reviewed-approved, 0-book-dash-may22

#2379 Update open.md
  book/website/reproducible-research/open.md
Labels: PR: reviewed-approved, 0-book-dash-may22

#2410 Github Action for Release Workflow testing
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-workflow.yml
  tests/release_workflow.py
Labels: PR: unreviewed

#2409 updates to different articles chapter
  book/website/_toc.yml
  book/website/communication/citable/citable-steps.md
  book/website/communication/dif-articles/reg.md
  book/website/project-design/pd-overview/pd-overview-methods.md
  book/website/reproducible-research/open/open-access.md
  book/website/reproducible-research/rdm/rdm-article.md
Labels: PR: reviewed-approved

#2405 Update style-figures.md
  book/website/community-handbook/style/style-figures.md
Labels: PR: unreviewed
