Repository the-turing-way/the-turing-way, pull requests merged in 2022-10, with the labels that each got.

#2669 Fix bash shell lexing problem
  book/website/reproducible-research/renv/renv-containers.md
Labels: PR: reviewed-approved

#2672 fix broken alt text formatting (must be on one line)
  book/website/reproducible-research/open/open-access.md
Labels: book-build, bug fixed, PR: unreviewed, PR: reviewed-approved, infrastructure, caretaking, accessibility

#2686 Correct top header levels in project design guide
  book/website/project-design/sdp/types.md
  book/website/project-design/sdpm/informed.md
Labels: project-design-book, PR: unreviewed, caretaking

#2687 Adding an alt image text
  book/website/community-handbook/style/style-figures.md
Labels: PR: reviewed-approved, community-handbook, accessibility

#2696 Fix figure name
  book/website/figures/binderhub.jpg
  book/website/figures/provenance.jpg
Labels: PR: unreviewed

#2676 Removal of duplicate "schedule" heading
  book/website/community-handbook/templates/template-coworking-weekly.md
Labels: PR: reviewed-approved

#2703 Added GitHub workshops to README
  workshops/README.md
Labels: PR: reviewed-approved

#2713 Set skipCI to true
  .all-contributorsrc
Labels: PR: reviewed-approved, infrastructure

#2667 Ml model licenses
  book/website/figures/rail-diagram.png
  book/website/reproducible-research/licensing/licensing-ml-case-studies.md
  book/website/reproducible-research/licensing/licensing-ml.md
Labels: PR: unreviewed

#2726 add ml license to TOC
  book/website/_toc.yml
Labels: PR: unreviewed

#2689 Restore contributing chapter
  book/website/community-handbook/contributing.md
Labels: PR: partially-approved

#2701 Update law-policy-rights.md
  book/website/ethical-research/law-policy/law-policy-rights.md
Labels: PR: reviewed-approved

#2720 fixing collaboration broken link
  book/website/communication/peer-review/peer-review-overview.md
Labels: PR: partially-approved

#2739 Update licensing-ml.md
  book/website/reproducible-research/licensing/licensing-ml.md
Labels: PR: unreviewed

#2737 enforcement edits
  book/website/reproducible-research/licensing/licensing-ml-case-studies.md
  book/website/reproducible-research/licensing/licensing-ml.md
Labels: PR: unreviewed

#2732 Lint and validate YAML files in CI
  .github/ISSUE_TEMPLATE/EDITOR_ISSUE_TEMPLATE.yml
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/contributors-record.yml
  .github/workflows/lorem-ipsums.yml
  .github/workflows/no-bad-latin.yml
  .github/workflows/test-file-size.yml
  .github/workflows/yamllint.yaml
  .yamllint
  CITATION.cff
  book/website/_toc.yml
Labels: PR: unreviewed

#2722 📝Fix typo and outdated labels on the French translation
  README-translated/README-French.md
Labels: PR: reviewed-approved

#2738 Update aa-overview.md
  book/website/communication/aa/aa-overview.md
Labels: PR: reviewed-approved

#2744 removing APC video link in open access chapter as no longer available
  book/website/reproducible-research/open/open-access.md
Labels: PR: reviewed-approved

#2749 Update new_chapter.yml
  .github/ISSUE_TEMPLATE/new_chapter.yml
Labels: PR: reviewed-approved

#2748 Cleanly exit the script if no matching issues are found
  .github/workflows/close-talk-issues.yml
Labels: PR: partially-approved

#2750 [Big Team Science Hackathon] Adding to the Research Infrastructure Roles list of job titles
  book/website/collaboration/research-infrastructure-roles.md
Labels: collaboration-book, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, book

#2757 adding final BTSCON roles + casing consistency
  book/website/collaboration/research-infrastructure-roles.md
Labels: PR: reviewed-approved

#2747 Update citable-orcid.md
  book/website/communication/citable/citable-orcid.md
Labels: PR: reviewed-approved

#2734 Create issue templates for regular events
  .github/ISSUE_TEMPLATE/BOOK_DASH_CHECKLIST.md
  .github/ISSUE_TEMPLATE/FIRESIDE_CHAT_CHECKLIST.md
Labels: PR: reviewed-approved, Hacktoberfest

#2759 fix typo in image filename
  book/website/figures/sensitive-data.jpg
  book/website/project-design/sdpm.md
Labels: typo-fix, PR: unreviewed, PR: reviewed-approved, PR: draft
