Repository the-turing-way/the-turing-way, pull requests merged in 2022-07, with the labels that each got.

#2457 Fix meaning of sentence 41
  book/website/reproducible-research/vcs/vcs-git-merge.md
Labels: PR: reviewed-approved

#2449 Fix typo in figure legend
  book/website/reproducible-research/overview/overview-barriers.md
Labels: PR: reviewed-approved

#2456 Fix typo in text
  book/website/reproducible-research/vcs/vcs-git-compare.md
Labels: PR: reviewed-approved

#2455 Small edits for clarity and consistency
  book/website/reproducible-research/vcs/vcs-git.md
Labels: PR: reviewed-approved

#2445 Update Anne contact information
  CONTRIBUTING.md
  book/website/afterword/contributors-record.md
  book/website/community-handbook/coc.md
  book/website/community-handbook/community-handbook.md
  book/website/community-handbook/contributing.md
  communications/promotion-pack/README.md
  contributors.md
Labels: PR: unreviewed

#2435 Fix typo while translating in Crowdin
  book/website/reproducible-research/overview/overview-barriers.md
Labels: PR: reviewed-approved

#2462 pull changes from main to the PR branch
  .all-contributorsrc
  CONTRIBUTING.md
  README.md
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/afterword/contributors-record.md
  book/website/community-handbook/coc.md
  book/website/community-handbook/community-handbook.md
  book/website/community-handbook/contributing.md
  book/website/ethical-research/ethics-open-source-governance.md
  book/website/figures/ladder-of-participation.jpg
  book/website/reproducible-research/open/open-data.md
  book/website/reproducible-research/overview/overview-barriers.md
  book/website/reproducible-research/vcs/vcs-git-compare.md
  book/website/reproducible-research/vcs/vcs-git-merge.md
  book/website/reproducible-research/vcs/vcs-git.md
  book/website/requirements.txt
  communications/promotion-pack/README.md
  contributors.md
Labels: PR: unreviewed

#2357 May 2022 newsletter
  communications/newsletters/images/2022-05-bookdash-hubs.jpg
  communications/newsletters/images/2022-05-collaboration-scriberia.jpg
  communications/newsletters/images/2022-05-community-scriberia.jpg
  communications/newsletters/images/2022-05-fireside-scriberia.jpg
  communications/newsletters/images/2022-05-hiddenref.jpg
  communications/newsletters/images/2022-05-jisc.jpg
  communications/newsletters/images/2022-05-mastodon-screenshot.jpg
  communications/newsletters/images/2022-05-rdm.jpg
  communications/newsletters/images/2022-05-scientific-pub-vicky.jpg
  communications/newsletters/images/2022-05-showtell.jpg
  communications/newsletters/images/2022-05-talks-workshops.jpg
  communications/newsletters/images/2022-05-tweets.jpg
  communications/newsletters/newsletter_34_May2022.md
Labels: PR: reviewed-approved

#2076 "Sensitive data projects"-subchapter for Project Design
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/afterword/glossary.md
  book/website/figures/senitive-data.jpg
  book/website/project-design/sdp.md
  book/website/project-design/sdp/biological.md
  book/website/project-design/sdp/combined.md
  book/website/project-design/sdp/confidential.md
  book/website/project-design/sdp/metadata.md
  book/website/project-design/sdp/pd-sdp-private-learning.md
  book/website/project-design/sdp/personal.md
  book/website/project-design/sdp/types.md
  book/website/project-design/sdpm.md
  book/website/project-design/sdpm/data-privacy-strategies.md
  book/website/project-design/sdpm/informed.md
  book/website/project-design/sdpm/resources.md
  book/website/project-design/sdpm/sharing-sensitive-data.md
  book/website/project-design/sdpw.md
  book/website/project-design/sdpw/pd-sdp-exposing-data.md
  book/website/project-design/sdpw/pd-sdp-private-learning.md
  book/website/project-design/sdpw/pd-sdp-resources.md
  book/website/project-design/sdpw/pd-sdp-sensitive-code.md
  book/website/project-design/sdpw/pd-sdp-sensitive-files.md
  book/website/project-design/sdpw/trew.md
Labels: work-in-progress, PR: unreviewed, PR: reviewed-approved

#2381 Personal story for RSE Asia
  book/website/_toc.yml
  book/website/collaboration/research-infrastructure-roles/community-manager.md
  book/website/collaboration/research-infrastructure-roles/data-steward-personal-story.md
  book/website/collaboration/research-infrastructure-roles/data-steward.md
  book/website/collaboration/research-infrastructure-roles/rse-personal-story.md
  book/website/collaboration/research-infrastructure-roles/rse.md
Labels: PR: partially-approved

#2467 Update rse-personal-story to update the figure format and image
  book/website/collaboration/research-infrastructure-roles/rse-personal-story.md
  book/website/figures/rse-community.jpg
Labels: PR: reviewed-approved

#2471 Create bookdash-illustrator chapter in Book Dash chapter
  book/website/_toc.yml
  book/website/community-handbook/bookdash/bookdash-illustrator.md
Labels: PR: partially-approved
