Repository the-turing-way/the-turing-way, pull requests merged in 2022-12, with the labels that each got.

#2889 [Ready for review] Minor tweaks to Sensitive data chapters
  book/website/project-design/sdpm/data-privacy-strategies.md
  book/website/project-design/sdpm/informed.md
  book/website/project-design/sdpm/resources.md
Labels: PR: reviewed-approved

#2909 Suggestions for the Code Style and Formatting page
  book/website/reproducible-research/code-quality/code-quality-style.md
Labels: PR: reviewed-approved

#2911 Adding David to Ways of Working
  ways_of_working.md
Labels: PR: reviewed-approved

#2912 Updating David's name!
  ways_of_working.md
Labels: PR: partially-approved

#2916 Minor error update in the chapter research objects
  book/website/communication/research-objects.md
Labels: PR: unreviewed

#2915 Update contributors.md with info from the Book Dash Nov attendees
  contributors.md
Labels: PR: reviewed-approved

#2920 Remove extra h1 to fix #2897
  book/website/collaboration/research-infrastructure-roles/data-wrangler.md
Labels: bug, book-build, PR: unreviewed, PR: draft, PR: partially-approved, caretaking
