Repository the-turing-way/the-turing-way, pull requests merged in 2022-09, with the labels that each got.

#2613 Remove redundant dependencies
  book/website/requirements.txt
Labels: PR: partially-approved

#2629 Convert EDITOR_ISSUE_TEMPLATE from markdown to YAML
  .github/ISSUE_TEMPLATE/EDITOR_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/EDITOR_ISSUE_TEMPLATE.yml
Labels: PR: unreviewed

#2589 Update activism-unionisation.md
  book/website/ethical-research/activism/activism-unionisation.md
Labels: PR: reviewed-approved

#2636 added name to project members in ways-of-working.md
  ways_of_working.md
Labels: PR: partially-approved

#2638 Formatting mistake in binderhub.md
  book/website/reproducible-research/binderhub.md
Labels: PR: reviewed-approved

#2635 Add The Netherlands to activism-unionisation.md
  book/website/ethical-research/activism/activism-unionisation.md
Labels: PR: unreviewed

#2621 add `journal` field to supress jupyter-book warning
  book/website/_bibliography/references.bib
Labels: PR: unreviewed

#2640 Fix referencing syntax
  book/website/project-design/sdpw/pd-sdp-private-learning.md
Labels: book-build, typo-fix, PR: unreviewed, PR: draft, PR: partially-approved, caretaking

#2641 BUG: fix glossary build warning
  book/website/afterword/glossary.md
Labels: book-build, PR: unreviewed, PR: reviewed-approved, caretaking

#2650 Added VU Amsterdam as contributor
  book/website/afterword/contributors-record.md
Labels: PR: reviewed-approved

#2651 Put VU contributors under VU Amsterdam
  book/website/afterword/contributors-record.md
Labels: PR: reviewed-approved

#2666 Update licensing-ml.md
  book/website/reproducible-research/licensing/licensing-ml.md
Labels: PR: unreviewed
