Repository the-turing-way/the-turing-way, pull requests merged in 2022-11, with the labels that each got.

#2763 Add peer review info
  book/website/communication/peer-review/peer-review-guidance.md
  book/website/communication/peer-review/peer-review-resources.md
Labels: PR: reviewed-approved

#2753 Add Research Infrastructure Developer profession
  book/website/collaboration/research-infrastructure-roles/research-infrastructure-developer.md
Labels: PR: reviewed-approved

#2773 [CI] Handle cases where talk_date cannot be extracted from the issue body
  .github/workflows/close-talk-issues.yml
Labels: PR: partially-approved

#2774 Delete duplicate info from managing senstive data
  book/website/project-design/sdpm/data-privacy-strategies.md
  book/website/project-design/sdpm/resources.md
  book/website/reproducible-research/rdm/rdm-personal.md
Labels: PR: reviewed-approved

#2591 Create presenting.md
  book/website/_toc.yml
  book/website/community-handbook/presenting.md
Labels: PR: unreviewed

#2765 update toc
  book/website/_toc.yml
Labels: PR: reviewed-approved

#2784 Updated recommended podcasts
  book/website/communication/podcasts.md
Labels: PR: reviewed-approved

#2783 Added cross reference to Confidential Data
  book/website/project-design/sdp.md
Labels: PR: reviewed-approved

#2785 Fixed typo line 55
  book/website/ethical-research/ethics-intro.md
Labels: PR: reviewed-approved

#2704 Removed extra +
  book/website/community-handbook/templates/template-coworking-collabcafe.md
Labels: PR: reviewed-approved, collaboration-workshop

#2792 Fixed typo
  book/website/ethical-research/ethics-intro.md
Labels: PR: reviewed-approved

#2789 Fixed typo in citation
  book/website/ethical-research/ethics-intro.md
Labels: PR: reviewed-approved

#2777 Fix typo: project-design/pd-overview/pd-overview-sharing
  .gitignore
  book/website/project-design/pd-overview/pd-overview-sharing.md
Labels: PR: reviewed-approved

#2800 Update 2022-11-14-carpentries.md
  workshops/github-workshop/2022-08-04-carpentriescon.md
Labels: PR: reviewed-approved

#2802 Corrected link
  book/website/reproducible-research/reviewing/reviewing-recommend.md
Labels: PR: reviewed-approved, 0-book-dash-nov22

#2804 Additional resources
  book/website/reproducible-research/rdm/rdm-fair.md
Labels: PR: reviewed-approved, 0-book-dash-nov22

#2724 Undefined labels
  book/website/afterword/contributors-record.md
  book/website/collaboration/research-infrastructure-roles/data-steward.md
  book/website/communication/new-articles.md
  book/website/scripts/contributors.sh
  tests/contributors.sh
Labels: PR: partially-approved, infrastructure

#2671 Update virtual environment build instructions
  book/README.md
Labels: PR: partially-approved, infrastructure

#2815 Adding in additional resources for OS governance on the Ethical Considerations for Open Source chapter
  book/website/ethical-research/ethics-open-source-governance.md
Labels: ethics-book, PR: unreviewed, PR: reviewed-approved, good first PR review, 0-book-dash-nov22

#2818 add software to delete personal data
  book/website/project-design/sdpm/data-privacy-strategies.md
Labels: PR: reviewed-approved

#2708 Add a link to cross-reference the subchapter on Metadata
  book/website/project-design/sdp.md
Labels: PR: reviewed-approved, collaboration-workshop

#2707 Add a link to cross-reference the sub-chapter on personal data
  book/website/project-design/sdp.md
Labels: PR: unreviewed, collaboration-workshop

#2706 Changed the cake emoji
  book/website/community-handbook/templates/template-coworking-collabcafe.md
Labels: PR: reviewed-approved, collaboration-workshop

#2812 fix formatting of tip block
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
Labels: PR: reviewed-approved

#2705 updated video link on line 30
  book/website/communication/citable/citable-steps.md
Labels: PR: partially-approved, collaboration-workshop

#2820 add anonimisation resources from another PR into managing sdp
  book/website/project-design/sdpm/data-privacy-strategies.md
Labels: PR: reviewed-approved

#2771 Update peer-review.md
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/communication/peer-review.md
  book/website/communication/peer-review/peer-review-code.md
  book/website/communication/peer-review/peer-review-open.md
  book/website/communication/peer-review/peer-review-resources.md
  book/website/reproducible-research/reviewing/reviewing-resources.md
Labels: PR: unreviewed, 0-book-dash-nov22

#2711 Fix broken link formatting on `reproducible-research/rdm/rdm-personal`
  book/website/reproducible-research/rdm/rdm-personal.md
Labels: PR: reviewed-approved, collaboration-workshop

#2822 [Ready for review] Update citations in Introduction to Book for Ethics
  book/website/_bibliography/references.bib
  book/website/ethical-research/ethics-intro.md
Labels: PR: reviewed-approved

#2839 Add journal fields to 2 references
  book/website/_bibliography/references.bib
Labels: bug, book-build, review request, PR: unreviewed, PR: reviewed-approved, infrastructure

#2837 fix non-consecutive headings
  book/website/community-handbook/presenting.md
Labels: book-build, review request, PR: unreviewed, PR: reviewed-approved, infrastructure

#2836 modify one of the orcid figure names to avoid a reference clash
  book/website/communication/citable/citable-orcid.md
Labels: book-build, review request, PR: unreviewed, PR: reviewed-approved, caretaking

#2835 remove duplicate template file
  book/website/communication/new-articles.md
Labels: review request, PR: unreviewed, PR: reviewed-approved

#2817 Added chapter on Data curation
  book/website/_toc.yml
  book/website/reproducible-research/rdm/rdm-data-curation.md
Labels: PR: unreviewed, 0-book-dash-nov22

#2845 Revert "fixing a whoopsie"
  book/website/community-handbook/presenting.md
Labels: bug, book-build, PR: unreviewed, PR: reviewed-approved, infrastructure

#2847 Updates to private learning chapter
  book/website/_toc.yml
  book/website/afterword/glossary.md
  book/website/project-design/sdpw.md
Labels: PR: reviewed-approved

#2375 [Ready for review] Research Object section in Communication
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/afterword/glossary.md
  book/website/communication/research-objects.md
  book/website/communication/research-objects/ro-concepts.md
  book/website/communication/research-objects/ro-implementation.md
  book/website/figures/research-object.jpg
Labels: PR: reviewed-approved, book-dash-may22, 0-book-dash-nov22

#2830 correct alt-text according to issue #2630
  book/website/reproducible-research/open.md
Labels: PR: reviewed-approved

#2859 minor follow up to #2830
  book/website/reproducible-research/open.md
Labels: book-build, PR: unreviewed, PR: reviewed-approved, caretaking

#2861 Add continuous integration so that build fails on jupyter-book warnings
  .github/workflows/ci.yml
Labels: PR: reviewed-approved

#2831 Add final link to SDP intro page
  book/website/project-design/sdp.md
Labels: PR: reviewed-approved

#2858 fix broken link in `project-design/sdpm/resources.md`
  book/website/project-design/sdpm/resources.md
Labels: PR: reviewed-approved

#2860 Remove duplicate chapter
  book/website/project-design/sdp/pd-sdp-private-learning.md
Labels: PR: reviewed-approved

#2857 delete figure list
  book/website/figures/_figure-list.md
Labels: book-build, PR: unreviewed, PR: reviewed-approved, infrastructure

#2805 Added name and info
  ways_of_working.md
Labels: PR: partially-approved

#2810 Updated section on personal data
  book/website/project-design/sdp/personal.md
Labels: PR: reviewed-approved, 0-book-dash-nov22

#2865 fix nonconsecuitive headers on `project-design/sdp/personal`
  book/website/project-design/sdp/personal.md
Labels: book-build, typo-fix, PR: unreviewed, PR: partially-approved

#2866 CI: update versions
  .github/workflows/ci.yml
  .github/workflows/contributors-record.yml
  .github/workflows/lorem-ipsums.yml
  .github/workflows/no-bad-latin.yml
  .github/workflows/release-workflow.yml
  .github/workflows/test-file-size.yml
  .github/workflows/yamllint.yaml
  book/website/reproducible-research/ci/ci-building-gh-actions.md
Labels: PR: reviewed-approved, infrastructure, caretaking

#1558 CI services chapter
  book/website/reproducible-research/ci/ci-options.md
Labels: PR: unreviewed, book-dash-nov20

#2852 Adding infrastructure maintainers to Ways of Working
  ways_of_working.md
Labels: PR: reviewed-approved, project governance, 0-book-dash-nov22

#2843 Moving chapters from remote collaboration to the main guide
  book/website/_toc.yml
  book/website/collaboration/chairing.md
  book/website/collaboration/coworking.md
  book/website/collaboration/event-participation.md
  book/website/collaboration/event-tools.md
  book/website/collaboration/informal-chats.md
  book/website/collaboration/new-community/new-community-teamwork.md
  book/website/collaboration/organising-conference.md
  book/website/collaboration/organising-meetings.md
  book/website/collaboration/remote-collab.md
  book/website/collaboration/remote-collab/remote-collab-guidelines.md
  book/website/collaboration/remote-collab/remote-collab-prosandcons.md
  book/website/collaboration/remote-collab/remote-collab-team.md
  book/website/collaboration/research-infrastructure-roles.md
Labels: PR: unreviewed

#2849 Update on the FAIR principles
  book/website/reproducible-research/rdm/rdm-fair.md
Labels: PR: unreviewed, 0-book-dash-nov22

#2850 Embedding video link into sensitive data overview intro
  book/website/project-design/sdp/types.md
Labels: PR: unreviewed

#2870 Update on the chapter on types of sensitive data
  book/website/project-design/sdp/types.md
Labels: PR: partially-approved, book, 0-book-dash-nov22

#2709 Update anonoymisation section in rdm-personal.md
  book/website/reproducible-research/rdm/rdm-personal.md
Labels: PR: unreviewed, collaboration-workshop

#2867 Added myself to contributors.md file after book dash 2022
  contributors.md
Labels: PR: partially-approved

#2872 [WIP] Adding a new chapter to the research ethics
  book/website/_toc.yml
  book/website/ethical-research/social-data.md
Labels: work-in-progress, ethics-book, collaboration-book, PR: unreviewed, PR: partially-approved, book, 0-book-dash-nov22

#2874 Update rdm-checklist.md
  book/website/_bibliography/references.bib
  book/website/reproducible-research/rdm/rdm-checklist.md
  book/website/reproducible-research/rdm/rdm-dmp.md
Labels: PR: reviewed-approved

#2806 Add Vagrant section
  Vagrantfile
  book/website/reproducible-research/renv/renv-virtualmachine.md
Labels: reproducibility-book, PR: unreviewed, PR: reviewed-approved, 0-book-dash-nov22

#2876 fix internal references RDM checklist
  book/website/reproducible-research/rdm/rdm-checklist.md
Labels: PR: reviewed-approved

#2878 Fix reference, per #2832
  book/website/project-design/sdp/personal.md
Labels: typo-fix, PR: unreviewed, PR: reviewed-approved, caretaking

#2875 Add cultural change
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/ethical-research/activism.md
  book/website/ethical-research/activism/activism-cultural-change.md
Labels: PR: unreviewed

#2883 Add Data-Wrangler sub-chapter
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/collaboration/research-infrastructure-roles/data-wrangler.md
Labels: collaboration-book, PR: unreviewed, PR: partially-approved, 0-book-dash-nov22

#2882 Fixed broken link
  book/website/project-design/project-repo/project-repo-roadmapping.md
Labels: PR: reviewed-approved, good first PR review
