Repository the-turing-way/the-turing-way, pull requests merged in 2022-02, with the labels that each got.

#2261 Update ram.md
  book/website/collaboration/research-infrastructure-roles/ram.md
Labels: PR: unreviewed

#2260 Adding a short section on RAMs
  book/website/_toc.yml
  book/website/collaboration/research-infrastructure-roles/ram.md
Labels: PR: unreviewed

#1850 Move Binder tutorial into the Comms Guide
  book/website/_toc.yml
  book/website/communication/binder.md
  book/website/communication/binder/zero-to-binder.md
  book/website/figures/binder-home.png
  book/website/figures/binder_notebook_banner.jpg
  book/website/reproducible-research/case-studies/case-study-statistical.md
  book/website/reproducible-research/renv/renv-binder.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-julia.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-r.md
  workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-solo.md
Labels: PR: partially-approved

#2263 Proofreading Guide for Project Design
  book/website/project-design/project-design.md
Labels: PR: reviewed-approved

#2267 Update rdm-metadata.md to remove redundant sentences
  book/website/reproducible-research/rdm/rdm-metadata.md
Labels: PR: reviewed-approved

#2265 Create rdm-article.md (WIP)
  book/website/_toc.yml
  book/website/reproducible-research/rdm/rdm-article.md
Labels: review request, PR: unreviewed, PR: reviewed-approved, good first PR review

#2275 Fix typo on CoC acknowledgements title
  book/website/_toc.yml
Labels: PR: reviewed-approved

#2253 Update ways_of_working.md to move UX project members under 'previous members'
  ways_of_working.md
Labels: PR: partially-approved
