Repository the-turing-way/the-turing-way, pull requests merged in 2023-04, with the labels that each got.

#2998 adds Plausible Analytics
  book/website/_config.yml
  book/website/requirements.txt
Labels: PR: unreviewed, infrastructure

#3034 case sensitive rename
  book/website/figures/Translation.jpg
  book/website/figures/adding-glossary.gif
Labels: PR: reviewed-approved

#3014 MAINT: remove mentions of travis
  CONTRIBUTING.md
  book/website/reproducible-research/ci/ci-resources.md
  book/website/reproducible-research/make.md
  book/website/reproducible-research/renv/renv-yaml.md
Labels: PR: reviewed-approved, infrastructure, caretaking

#3028 Create team-manual.md
  book/website/_bibliography/references.bib
  book/website/_toc.yml
  book/website/collaboration/event-tools.md
  book/website/collaboration/organising-meetings.md
  book/website/collaboration/team-manual.md
  book/website/communication/aa.md
Labels: PR: reviewed-approved

#2380 Add template for the translation
  .github/ISSUE_TEMPLATE/Request-Translation
Labels: translation, PR: unreviewed, book-dash-may22

#3016 MAINT: adding raise_for_status
  tests/pull_files.py
Labels: PR: reviewed-approved, infrastructure

#3029 Update example reference
  book/website/community-handbook/style/style-citing.md
Labels: PR: reviewed-approved, good first PR review

#3041 image formatting (minor tweaks)
  book/website/collaboration/oss-sustainability/oss-sustainability-challenges.md
  book/website/collaboration/research-infrastructure-roles/research-infrastructure-developer.md
  book/website/collaboration/research-infrastructure-roles/rse.md
  book/website/community-handbook/style/style-figures.md
  book/website/figures/oss-sustainability-pathways-problem.jpg
  book/website/figures/oss-sustainability-pathways-problem.png
  book/website/figures/oss-sustainability-pathways-solution.jpg
  book/website/figures/oss-sustainability-pathways-solution.png
  book/website/index.md
Labels: PR: reviewed-approved

#3013 Update newsletters-process with Zenodo link and missing sections
  book/website/community-handbook/newsletters/newsletters-process.md
Labels: PR: reviewed-approved

#3047 Add a redirect to welcome.html
  netlify.toml
Labels: PR: reviewed-approved
