Repository the-turing-way/the-turing-way, pull requests merged in 2023-03, with the labels that each got.

#2971 edit instructions on Google Scholar citations so it will also make se…
  book/website/community-handbook/style/style-citing.md
Labels: PR: unreviewed

#2975 Remove mention of developing a hosting guide from collab cafe page
  book/website/community-handbook/coworking/coworking-collabcafe.md
Labels: PR: partially-approved

#2985 Add checklist and responsibility document for Fireside chat
  .github/ISSUE_TEMPLATE/BOOK_DASH_CHECKLIST.md
  .github/ISSUE_TEMPLATE/FIRESIDE_CHAT_CHECKLIST.md
  book/website/_toc.yml
  book/website/community-handbook/fireside-chat.md
  book/website/community-handbook/fireside-chat/fireside-chat-checklist.md
  book/website/community-handbook/fireside-chat/fireside-chat-roles.md
Labels: PR: unreviewed

#2922 Local-build-instructions
  book/website/_toc.yml
  book/website/community-handbook/local-build.md
Labels: PR: unreviewed

#2994 Move welcome to index.md
  book/website/_config.yml
  book/website/_redirects
  book/website/_toc.yml
  book/website/collaboration/shared-ownership/shared-ownership-defaults.md
  book/website/index.md
Labels: PR: partially-approved

#2990 Update fireside chat chapters - editing/review
  book/website/community-handbook/fireside-chat.md
  book/website/community-handbook/fireside-chat/fireside-chat-checklist.md
Labels: PR: reviewed-approved

#2987 edit alt-text to be more informative
  book/website/_redirects
  book/website/reproducible-research/reproducible-research.md
Labels: PR: unreviewed, accessibility

#3000 Redirect fix
  book/website/_redirects
  netlify.toml
Labels: PR: partially-approved

#3001 Redirect fix (take two)
  netlify.toml
Labels: PR: partially-approved

#3002 Fixing the landing page deployment
  netlify.toml
Labels: PR: reviewed-approved

#3010 add chris to list of contributors
  ways_of_working.md
Labels: PR: reviewed-approved

#2926 Update the website footer to remove copyright assertion, and replace it with a link to the project licenses
  LICENSE.md
  book/website/LICENSE.md
  book/website/_config.yml
Labels: project management, PR: unreviewed, PR: reviewed-approved, project governance, infrastructure

#2995 Fixed dead link to eScience Center language guides
  book/website/reproducible-research/code-quality/code-quality-style.md
Labels: PR: reviewed-approved

#2963 Updated files for new release and update release-workflow.md to add a missing step
  .zenodo.json
  CITATION.cff
  release-workflow.md
Labels: PR: partially-approved
