Repository the-turing-way/the-turing-way, pull requests merged in 2023-02, with the labels that each got.

#2930 Add alt texts properly in the style guide
  book/website/community-handbook/style/style-figures.md
Labels: PR: partially-approved

#2959 Update research-infrastructure-roles.md to make sure we don't categorise them as 'support'
  book/website/collaboration/research-infrastructure-roles.md
Labels: PR: unreviewed

#2964 I added myself to the team
  ways_of_working.md
Labels: PR: reviewed-approved

#2969 Update unions page with more recommendations
  book/website/ethical-research/activism/activism-unionisation.md
Labels: ethics-book, PR: unreviewed, PR: reviewed-approved

#2951 Update rdm.md
  book/website/reproducible-research/rdm.md
Labels: PR: reviewed-approved

#2968 adding mself to ways of working
  ways_of_working.md
Labels: PR: reviewed-approved

#2974 Useful Resources subchapter for remote collab
  book/website/_toc.yml
  book/website/collaboration/remote-collab/remote-collab-useful-resources.md
Labels: PR: partially-approved
