Repository the-turing-way/the-turing-way, pull requests merged in 2023-01, with the labels that each got.

#2929 Adding data-wrangler illustration
  book/website/collaboration/research-infrastructure-roles/data-wrangler.md
  book/website/community-handbook/style/style-figures.md
  book/website/figures/data-wrangler.jpg
Labels: collaboration-book, PR: unreviewed, PR: partially-approved, book, 0-book-dash-nov22

#2934 Giving a talk illustration
  book/website/community-handbook/presenting.md
  book/website/figures/giving-a-talk.jpg
Labels: PR: partially-approved

#2943 Adding Shakir to WoW doc
  ways_of_working.md
Labels: PR: reviewed-approved

#2925 add missing space
  book/website/project-design/project-repo/project-repo-advanced.md
Labels: typo-fix, approval request, PR: unreviewed, PR: reviewed-approved

#2924 Remove (presumably) unintended links to the websites `readme.md` and `license.md`
  book/website/collaboration/github-novice/github-novice-features.md
  book/website/collaboration/github-novice/github-novice-firststeps.md
  book/website/reproducible-research/licensing/licensing-checklist.md
Labels: typo-fix, PR: unreviewed, PR: reviewed-approved, caretaking

#2891 RDM chapter update
  book/website/_bibliography/references.bib
  book/website/communication/citable/citable-cite.md
  book/website/project-design/sdpm/data-privacy-strategies.md
  book/website/project-design/sdpm/informed.md
  book/website/reproducible-research/compendia.md
  book/website/reproducible-research/open/open-data.md
  book/website/reproducible-research/rdm.md
  book/website/reproducible-research/rdm/rdm-checklist.md
  book/website/reproducible-research/rdm/rdm-data-curation.md
  book/website/reproducible-research/rdm/rdm-data.md
  book/website/reproducible-research/rdm/rdm-dmp.md
  book/website/reproducible-research/rdm/rdm-metadata.md
  book/website/reproducible-research/rdm/rdm-resources.md
  book/website/reproducible-research/rdm/rdm-sharing.md
  book/website/reproducible-research/rdm/rdm-spreadsheets.md
  book/website/reproducible-research/rdm/rdm-storage.md
Labels: PR: unreviewed

#2251 Add a GitHub Action to automatically compress image files
  .github/workflows/auto-compress-images.yaml
Labels: PR: partially-approved
