Repository the-turing-way/the-turing-way, pull requests merged in 2024-10, with the labels that each got.

#3828 Adding latest set of images in the figure folder
  book/website/figures/accessible-learning-paths.jpeg
  book/website/figures/ambassador-program-roche.jpeg
  book/website/figures/ambassador-program.jpeg
  book/website/figures/case-study-framework.jpeg
  book/website/figures/creative-data.jpeg
  book/website/figures/data-repo.jpeg
  book/website/figures/embedding-justice.jpeg
  book/website/figures/feedback-loop-process.jpeg
  book/website/figures/learning-levels.jpeg
  book/website/figures/linting-no.jpeg
  book/website/figures/missing-data.jpeg
  book/website/figures/open-development.jpeg
  book/website/figures/peer-learning.jpeg
  book/website/figures/performative-wokeness-2.jpeg
  book/website/figures/performative-wokeness.jpeg
  book/website/figures/r-development-guide.jpeg
  book/website/figures/transformational-teaching.jpeg
  book/website/figures/turing-way-governance-2.jpeg
Labels: Hacktoberfest, 0-book-dash-june24

#3846 Remove banner
  book/website/_config.yml
Labels: infrastructure, maintenance

#3788 adding notes from community forum
  governance/community-calls/20240215-community-forum.md
  governance/community-calls/20240422-coworking copy.md
  governance/community-calls/20240423-community-forum.md
  governance/community-calls/20240712-community-forum.md
Labels: notes

#3512 Update python and sphinx for HTML deployment
  .github/workflows/ci.yml
  .github/workflows/close-talk-issues.yml
  .github/workflows/external_link_check.yml
  .github/workflows/lorem-ipsums.yml
  .github/workflows/no-bad-latin.yml
  .github/workflows/validate-all-contributorsrc.yml
  .github/workflows/yamllint.yaml
  book/Makefile
  book/website/community-handbook/local-build.md
  book/website/requirements.in
  book/website/requirements.txt
  netlify.toml
Labels: infrastructure
