Repository the-turing-way/the-turing-way, pull requests merged in 2024-02, with the labels that each got.

#3519 Introducing Blobless Clones to Address Slow Internet Connections
  book/website/community-handbook/local-build.md
Labels: infrastructure, accessibility

#3527 Create Notes from PM-Core-team-Meetings-12Feb24.md
  governance/pm-core-meeting-notes/pm-core-202402012.md
Labels: project governance

#3531 Add Crowdin contributors table to afterword
  .github/workflows/crowdin-contributors.yml
  README.md
  book/website/afterword/contributors-record.md
Labels: infrastructure

#3552 [Ready for Review] adding backlog of coworking call notes
  governance/community-calls/20240129-coworking.md
  governance/community-calls/20240205-coworking.md
  governance/community-calls/20240212-coworking.md
  governance/community-calls/20240219-coworking.md
  governance/community-calls/20240226-coworking.md
Labels: notes
