Repository the-turing-way/the-turing-way, pull requests merged in 2024-04, with the labels that each got.

#3603 [Ready for review] Update to patched version of pillow.
  book/website/requirements.txt
Labels: infrastructure

#3523 Update hybrid-collab-guidelines.md
  book/website/collaboration/hybrid-collab/hybrid-collab-guidelines.md
Labels: review request, PR: unreviewed, accessibility

#3285 Upload Book Dash WG meeting notes from September 2023
  workshops/book-dash/meeting-notes/2023-09-05-WG.md
Labels: idea-for-discussion, 0-book-dash-nov23, notes
